### ISSUE TITLE
[Question] Can I build it for Linux Ubuntu?

### ISSUE THREAD

**Issue by escaroda** [johanneszab/TumblThree#1]
Hi. Thanks for a great software!
I'm not into C Sharp so I don't know anything about this language but I believe if it's possible I would compile this app for Linux (Ubuntu). I just need to make sure that it's real without changing code. Can I do that? Or there are something windows specific? (folder structure for example)

**Comment by johanneszab** [comment]
Hiya,

C# will run on Linux using Mono. Since Microsoft recently released the common language runtime (CLR) under an open source license, and brought Ximian (main developer of mono), it may improve significantly over time.

However, the UI in WPF (Windows Presentation Framework) won't work under Linux. Mono currently only supports WinForms. Also, there is no designer for WinForms under Linux.
So, someone has to put together a new UI in Gtk# or similar for the application. That's what I was planing on doing someday after I've fixed the most major bugs.

The clipboard monitor also won't work as it uses Win32 apis. In [TumbTwo](https://github.com/johanneszab/TumblTwo), which is written in C# as well but uses WinForms -- so it works mostly "out of the box" on Linux -- I briefly looked into clipboard events under Linux and its quite a mess. I think it's probably as there is no _the desktop_ under Linux but many different environments and window manager.

So, I can think of these two things which certainly have to be addressed before the application will run.

**Comment by speciose** [comment]
I am thinking about creating similar software using node.js and electron.
Could you help me understand a key idea about how your tumblr crawler works? Do you crawl web pages or using json api?
