### ISSUE TITLE
Download speed falls off after some period of time?

### ISSUE THREAD

**Issue by johanneszab** [johanneszab/TumblThree#101]
Since I don't use TumblThree myself at all and finally had some time for profiling over the weekend, I've noticed that the download speed suddenly decreased drastically to a few (3-5) MBit/s. Can anyone else confirm this? Like after 30-40 minutes of download?! It probably depends on the download/connection speed too.

If that's the case, but not for the [v1.0.4.31 release](https://github.com/johanneszab/TumblThree/releases/tag/v1.0.4.31) before the code refactoring, its probably something in the (async) code. It could also be a wanted behavior server side or related to my system/network, that's why I'm asking.

Thanks!

PS: I've also noticed a heavily fragmented heap, but I don't know if that can be related at all.

**Comment by Taranchuk** [comment]
I did not notice anything that changed in terms of download speed and after 30 minutes and after a few hours of download. But my Internet speed is lower, somewhere 1 MBit/s, so I do not know what will happen in a situation where the speed of the Internet is much greater.

> I've also noticed a heavily fragmented heap

I did not quite understand what it is, because I'm not very strong in English, but it's about the not completely downloaded images, so in the images below there are gray bars, then yes, I have such images, somewhere a few dozen on tens of thousands of downloaded files usually. I just find them by a special program for searching non-completed images, delete them and then run the crawling with forced scanning and everything is downloaded completely.

**Comment by A-Cat-Named-Tiger** [comment]
![capture](https://user-images.githubusercontent.com/25445438/27569000-2050912a-5b30-11e7-8817-08d279107cc8.PNG)

When I tested, above results came out. First screenshot is taken 5 minutes after I started crawling and second shot is taken after 40 minutes.
It seems that downloading speed is somewhat decreased, however, I think that is due to writing speed of the disk drive D. Once the drive's 'Active time' reaches 100%, it appears to slow down the write speed of the drive (it was average 2.3 Mb/s).

![3](https://user-images.githubusercontent.com/25445438/27569290-c72953a0-5b31-11e7-8a41-912bcf60cbda.PNG)

The 'Active time' started to decrease 5~10 minutes after I stopped crawling and exited the program.


+ I also observed some fragmented images and videos

**Comment by johanneszab** [comment]
Thanks for the reports and the nice screenshots! Then it's hopefully only on my side and nothing with the application itself.

**Comment by keokitsune** [comment]
I have noticed that the most recent update downloads super slow, the first update that implimented the RAW download option still downloads at the old speed but if I switch to anything newer I only get about I picture download a second. But if I try to go back the the older vertion it says im doanloadiung files but the counter no longer goes up.
