### ISSUE TITLE
_raw image file detection

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblThree#106]
Hi Johannes,

I think there might be a bug wit tumblthree. Before in the past, as you know, we could stop and start crawls easily. But now, when I click "stop" the "crawl" button stays grayed out and I can't restart a crawl. I have to close the application each time and pretty much tart from the beginning each time. Has anyone else brought this issue up?

**Comment by johanneszab** [comment]
Yes, I notice it too.

That's why I removed the newer releases from the weekend this morning. I'm sure it's in the new code, but it's so simple and I really was sure that there couldn't be anything wrong it, that I cannot believe it actually ;).

I'll fix it tonight once I'm back from work.

**Comment by johanneszab** [comment]
Thanks for reporting!

**Comment by Linktydraa** [comment]
cool beans. Thank you.

**Comment by johanneszab** [comment]
I don't think there is an easy fix. The code doesn't seem to be wrong in general, it's just probing to many urls now in order to get the right *_raw* image host and sometimes the server respond with _gateway timeout_ (which they never did before).

It's also way slower (network/internet I/O has large latency) to test all the urls/hosts so that the url crawler finishes way sooner than the downloader actually starts downloading anything.

Overall, It kinda sucks having to try out several different hosts in order to download anything. I'm not aware of a proper solution right now, and before it's weekend I also won't have time to test this properly.

**Comment by JAK0723** [comment]
I'm not sure if you're aware of this yet, but removing the first 2 numbers of a tumblr image's url (eg https://media.tumblr.com/) can allow to access the raw file without getting a 404 error.

**Comment by Linktydraa** [comment]
there also seems to be a problem with downloading images from certain tumblrs. The tumblrs that just have scrolling and images poping up as you scroll to the bottom, do not seem to be downloading all the images vs tumblrs that have actual pages. Has anyone had this issue before?

**Comment by johanneszab** [comment]
@JAK0723 

Not true. All the crappy releases from the last week are due to finding a proper way to get _raw images without dropping non-raw images that cannot be accessed with the _raw url. Without introducing to much latency, hitting rate limits, or other unforeseen events. 

They seem to be uploaded to the servers/introduced at sometime December 2012:

![raw_files_dec_2012](https://user-images.githubusercontent.com/1684561/28229676-e9e4cb4e-68e3-11e7-8ec0-a275f0dc4c30.png)

**Comment by JAK0723** [comment]
@johanneszab 
Oh that's it? Yeah, turns out that raw files didn't exist before December 2012 or thereabouts, trying to access them that early will just give you errors.
