### ISSUE TITLE
It seems to be ignoring the 'Download Reblogged' checkbox

### ISSUE THREAD

**Issue by FilthyLiquid** [johanneszab/TumblThree#110]
It still downloads reblogs even if it's left unchecked.

**Comment by johanneszab** [comment]
Works for me.

Please, this is no real bug report. State at least your version, the blog you've downloaded and how you set up the download. And how you've tested if it actually works. Otherwise I cannot reproduce the issue.

I've just tested it, no issue here. It does however not work on private blogs or _LikedBy_ downloads as it's not implemented there.
