### ISSUE TITLE
Why some tumblr blogs just offline when I begin to crawl

### ISSUE THREAD

**Issue by zhongtao93** [johanneszab/TumblThree#114]
Some tumblr blogs cannot crawl but others work well. Did I do something wrong?

**Comment by johanneszab** [comment]
How am I supposed to answer this?

You could at least have specified your TumblThree version and state a non-functional blog. Based on your question, there is _nothing_ I can tell you.

Next time, you you either ask a solid question or you have an reproducible issue with instructions. Otherwise I honestly don't understand what the purpose of opening this _issue_ is.

**Comment by johanneszab** [comment]
Maybe you still want to give the the latest version v1.0.8.5 a try. Remove your offline blogs and re-add them.

If you then still have your issue, please report with detailed steps on how to reproduce your error.
