### ISSUE TITLE
Distinguishing "Offline" and "Safe mode"

### ISSUE THREAD

**Issue by A-Cat-Named-Tiger** [johanneszab/TumblThree#115]
![image](https://user-images.githubusercontent.com/25445438/28778908-4015a1fe-763c-11e7-9e53-d48521766955.png)
Some blogs are displayed as offline while they can be accessed through an account that has disabled "Safe mode" feature. Above picture shows how user access is denied without login. Wouldn't a refresh feature or connectivity recheck after authentication be able to solve this problem?

**Comment by johanneszab** [comment]
Please _always_ include _all steps_ so that I can reproduce the issue, otherwise opening the issue is meaningless. That should honestly be common knowledge.
So, what's the url of the blog in that picture? Version of your TumblThree?

I'm explicitly asking because I've already tested blogs which need a login to get beyond the safe mode to access them and they work without doing anything. Thus, I can not troubleshoot this nor fix anything. I.e. your issue report is useless.

**Comment by johanneszab** [comment]
I think version 10.8.5 does fix or at least improve your issue.

Thanks for posting. It was indeed some kind related to safe-mode blogs.
