### ISSUE TITLE
Blog that is only visible on Dashboard cannot be downloaded

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#118]
I am trying to add a blog, that is configured to open only in the sidebar in Tumblr Dashboard. I was under the assumption, that using "settings" -> "authorise" would allow us to parse that and using tags to download images etc. However, that blog does not seem to work and there is no error message. Clicking on "Authorise" again, does open the little browser window but it closes again right away, nor does it return an error. 

1. How can I check if I am still properly authorised?
2. Is there a log I can check to provide more info for troubleshooting? 

Thanks and cheers for the great app :)

**Comment by johanneszab** [comment]
Name of the blog?

**Comment by Kvothe1970** [comment]
Hi Johannes, thank you for the quick reply. The blog in question is: loves-fool.tumblr.com

**Comment by Kvothe1970** [comment]
Addon, I can see the downloader is trying something, it say "1 Tumblrblgoseite ausgewerted" and then it just stops. The blog shows as "online" in the list.

**Comment by johanneszab** [comment]
Okay, for me it's working here. It just continues with several "Tumblrseite ausgewertet"/"evaluated X tumblr pages" until the post counter reaches 1160 posts. My desktop system is in English though, maybe it is an issues with the translation and it breaks something. Would be odd, but maybe that's the case.

I'll test it later on my German notebook. If you want to check it briefly, all you have to do is temporarily moving out the 'de' folder of the TumblThree main folder before starting TumblThree. It should be running in English if it doesn't find the 'de' folder. Just start the download and test if it's working then..

So, but in principle you're doing everything right.

1. If the authenticate window closes immediately after opening it means you're still logged in. It basically is a Internet Explorer within a window. Thus, the cookie you generate during the login procedure is also stored in the Internet Explorer files. I don't know the exact expire date Tumblr.com sets on it's cookies since I regularly remove all cookies again and again during testing, but it lasts several days/week. 
    
    You can check it in the Internet Explorer->Settings Wheel->Internet Options->General->Browser History->Settings->View Files. In the Explorer window which opens you'll see a files called _cookie:username@tumblr.com_ which is the cookie. It's should be somewhere under _C:\Users\Username\AppData\Local\Microsoft\Windows\INetCache_.

**Comment by Kvothe1970** [comment]
I am still logged in, there are three cookies which seems normal @srvcs.tumblr.com @tumblr.com and www.tumblr.com 
btw I tried both with a Tags entry and without, no success. 

I also temporarily removed the de folder. Started the app, added the blog and told it to crawl. Same result.

**Comment by johanneszab** [comment]
Err, I'm not sure if I've ever tested the "private downloader" with tags properly because how the posts are displayed on the tumblr website within the dashboard is kinda ridiculous imho. But If you say it doesn't even work without tags, then it's strange. It should be the exact same thing I've done then.

You're using TumblThree version v1.0.8.5?

**Comment by Kvothe1970** [comment]
Yes, I am using 1.0.8.5 at the moment. 
I removed the blog, restarted, added again. No luck. 
I mean if it won't work it won't work, but it is still confounding.

**Comment by johanneszab** [comment]
You could try to remove the settings in C:\Users\Username\AppData\Local\TumblThree\Settings\ but I don't think that will help.

It's kinda weird, yapp. I haven't implemented any logging whatsoever. I didn't want to for privacy reasons. Also implementing a diagnose thingy properly with securely sending anonymous data isn't the easiest thing if it should be done right.

**Comment by johanneszab** [comment]
Anyone else having problems with the same sympotom (the crawler stalls at evaluating pages) while downloading private blogs?

@Kvothe1970:
Is that specific to that blog, or does it happen with all private blogs? Did you try leaving all the default settings execpt for the download location? Maybe a specfic setting I've not checked interferes with the crawler somehow. I usually only change the download location, parallel blogs and parallel connections settings.

**Comment by Kvothe1970** [comment]
@johanneszab I am honestly not sure. But I did remove the settings and nothing changed. I can try again tonight though. I have to check if I have other private blogs in my list. Unless you have one handy I could try. I will update you tonight.

**Comment by Kvothe1970** [comment]
Okay then, I downloaded TumblrThree on a different system with Win10, added the blog mentioned above and it works. That makes no sense to be honest. What would be the best way, to retain all blogs in my home install and reset the settings? Also, could this be an issue with the Index Folder? If I remember correctly you moved the location of the Index at some point. However, I retained the original folder structure so there is a folder with Index information in the "Blogs" folder.

**Comment by Kvothe1970** [comment]
Now I am home. I went and copied the files from the "other" Index Folder and placed them in my local Index Folder. Tried to download the blog here again, and the same result.

**Comment by johanneszab** [comment]
I'm still at work and cannot test anything here, but can try to manually remove all the loves-fool* files  from the Index folder? Close TumblThree before doing that. Maybe I haven't adjusted the delete method for private blogs as the suffix for those databases should be different (e.g. not .tumblr).

Just remove everything starting with loves-fool.

**Comment by Kvothe1970** [comment]
I closed the app, removed all the files. Started the app and added the blog again. Same result. 
I added another private blog. It start the same (parsing the page) but then continues and starts downloading.

**Comment by johanneszab** [comment]
So? I cannot really help you remotely without having real error messages or Visual Studio installed, thus you'll probably have to figure it out yourself.

It changes now depending on your Windows version or installation? I only test the code on Windows 10, but I don't think that Microsoft has different behaviors/side effects of the same code on different Windows versions with its .NET runtime.

**Comment by Kvothe1970** [comment]
The windows version is the same, but it is a different installation on a different system. The OS and version is the same (both windows 10) The weird this is, that another private blog works fine on the original install. Both Win 10 installs have the same .NET Framework versions installed (via Windows Update, latest version). 
So baffling, especially since I went and removed the config to try it out back when you asked me to try that too.

**Comment by Linktydraa** [comment]
i'm still having issue with this problem as well :(

**Comment by johanneszab** [comment]
As I've said earlier, I cannot fix this with the current available information. So your post makes no sense.

Either you debug it yourself, or you tell me something new. Just writing: "I've the problem too" is useless.

Whats your TumblThree version?
Can you download the blog from above?
Can you download any private blog at all? Please try at least two since It seems to have work for Kvothe1970 with a different blog for some reason.
Are you sure you're authenticated?
Do you have the same symptoms? I.E. "Evaluated 1 blog site" and then it stops?
Whats happens if you try to download a private blog?
