### ISSUE TITLE
The new function of downloading by tags downloads a lot less files than it should be

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#125]
I tried downloading the link https://www.tumblr.com/tagged/lucy+pinder
And found that the program downloaded only 28 images, but I looked through the link how many images there should be on the page, it seems to me a lot more images should be because I long scrolled down until the browser hangs but did not reach the end of the page and there must be at least a thousands of images. Could you improve somehow the detection algorithm since it is clearly imperfect and does not download all images on the page? 
P.S. Thanks for the new features! With the link https://www.tumblr.com/search/lucy+pinder, the program downloaded 3061 images, I do not know if it's all images on this search page, but it's already very good for me. I still do not know if you know, but there is still another a search page /recent (example https://www.tumblr.com/search/lucy+pinder/recent), there may seem to be other images than on the top search page, you can add support for this page if it not difficult.

**Comment by johanneszab** [comment]
the problem is the +. 

If you use single tag it works right now. I'll fix it later today.

**Comment by johanneszab** [comment]
The queue restore is also broken if multiple "blogs" have the same time since i'm only storing the blogs name. I wanted it lightweight, now it's easy. For example if you search for lucy+pinder in the /tagged/ search and in the /search/ search the restore picks the first entry in the list.

Also I'm not sure If we should add a maximum number of pages to search. It tag search goes back until 2007 or something so it could potentially return a lot of stuff. At some point TumblThree will probably crash since most data structures can only handle 2GB unless this [option is set](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element) and I haven't tried it out yet.

**Comment by Taranchuk** [comment]
> Also I'm not sure If we should add a maximum number of pages to search. It tag search goes back until 2007 or something so it could potentially return a lot of stuff. At some point TumblThree will probably crash since most data structures can only handle 2GB unless this option is set and I haven't tried it out yet.

Personally, I do not want any limit, if I see that the program has downloaded too many files, I'll just stop downloading. And here it seems already there is a function of downloading specific pages, for example if need to download only 1000 posts, any user can specify a limit of 1-1000 in the details view.

**Comment by johanneszab** [comment]
I also have to replace the - with a + if the user is logged in.

I think can add two textboxes to specify a time span in which to crawl for tagged images. This way one could download in batches and there is no fixed limit.
