### ISSUE TITLE
Fehler 1 Die Downloadliste konnte nicht geladen werden Version 1.0.8.16

### ISSUE THREAD

**Issue by Kvothe1970** [johanneszab/TumblThree#129]
Hi, 

since the last update I performed to version 1.0.8.16 I get this error message. But all blogs seem to be still there. 

![fehler 1](https://user-images.githubusercontent.com/24984994/29747749-8bc98b60-8b04-11e7-8dc8-aed18fd8357b.png)

1. What can I do to fix this? 
2. Can I check the blog list manually against the entries in the db? 
3. Considering the "internal error" did I cause this somehow?

**Comment by johanneszab** [comment]
No, I did this deliberately since I needed more information stored in the queue save file. Otherwise it could have happen that you'd add a www.tumblr.com/search/_mysearch_ and a www.tumblr.com/tagged/_mysearch_ and the wrong thing would be downloaded after a program restart.

Thus, it only tells you that your queue is gone. There is nothing wrong with your blogs. You'll have to manually re-fill our queue. Sorry for this.

**Comment by Kvothe1970** [comment]
Don't worry, nothing to be sorry for, Johannes. You do an amazing job on this. 
Just to be clear. I will have to remove the blogs and re-add them again to the list of blogs, including adding the tags etc. Will the previously already downloaded content still be recognized by this?

**Comment by johanneszab** [comment]
No, you only have to re-add things to the right, smaller tab that shares its place with the Details tab. I think I've named it "Downloadliste" in German.

You don't have to delete anything, just re-add the blogs you want to actively download. You don't need to modify any of your blogs and nothing is lost.

**Comment by Kvothe1970** [comment]
Ah okay, actually my queue is empty and always is after I finish my regular updates. That is why I asked because that is what I looked at when you mentioned the queue.
