### ISSUE TITLE
Upgrading from 1.0?

### ISSUE THREAD

**Issue by Jalbre2** [johanneszab/TumblThree#13]
I have been trying to move from TumblThree 1.0 to any of the newer versions for a while, and I have been unsuccessful. I'm not sure if my index files are the problem or what.

On 1.0.1, the blogs will be evaluated, and then clear from the list without downloading anything.

On newer versions, like 1.0.2.4 and 1.0.4.3, the same thing happens, but the "Number of Images" column for said blog will be cleared at the end of the evaluation.

I delete the appdata before trying a new build, and I will go into the settings after first launch and change a few things to make sure it is set properly. What do I need to do to upgrade to the newer versions without starting from scratch? Redownloading absolutely everything isn't really an option for me.

**Comment by johanneszab** [comment]
Actually, this time I really took care to not mess up the internal .index file structure even if their meaning changed over the time.

I've just downloaded the 1.0 version, created a blog and downloaded some files. Then I stopped and moved the \Blog\ folder into the newest 1.4.3 version. Everything comes up, but you have to apply your search settings now for each blog individual. Since those settings were not implemented into the 1.0 version, since they were handled via the _settings_ windows. Now you have to set the checkboxes for each (imported) blog in the _Details_ windows on the right side.

Therefor, select all blogs in the manager (right list) with ctrl-a, then select the _Details_ windows on the right side instead of the queue. Here you have to select _No of 'post type'_ for each kind you want to download. So, for example select _No. of Photos_ to download images. The settings are saved for each selected blog on the left side. I've done this for a more finer tuning since you can populate the queue now with your wanted blogs and load videos for the one, but images for the other.

I hope that helps.

**Comment by Jalbre2** [comment]
Thank you, that fixed it for me! Much appreciated. I'm very happy to be able to use the latest version now.

I like that change as well, it absolutely makes sense with all of the additions that have been made to the program. Keep up the good work, I'll throw another donation your way soon!

**Comment by Jalbre2** [comment]
Thanks again!
