### ISSUE TITLE
Crash with 'Check Clipboard' option activated

### ISSUE THREAD

**Issue by Dexyne** [johanneszab/TumblThree#135]
Hello!

So I'm currently using TumblThree version 1.0.8.20 on Windows 10 and each time I copy an URL with the 'check clipboard' option on, the program crash.
The portable mode is not activated and some other options set as activated by defaut were set to off.

Deactivating it seems to 'fix' the issue.

**Comment by johanneszab** [comment]
Since this doesn't happen to me, and I'm using Windows 10, there most be more different with your system than you're saying. Since I cannot reproduce this, either you'll have to fix it, or you'll have to tell me more about your system.

For example, what could be relevant:
* What browser do you use? Does it happen with any text, regardless of where it's copied? For example also in an editor?
* Is your windows virtualized? Since the Clipboard Monitor uses Windows .dlls there might be some other software that also access/modifies those .dll at the same time.
* Anything other relevant changes compared to a standard Windows? Any meaningful non-standard background task?! (For example, AV, emulation/virtualization, etc..)
* Whats your Windows language set to? I doubt this has an impact, since apparently people use it with Chinese and Russian localization, and I've tested it with German and English, but .. maybe.

**Comment by Dexyne** [comment]
I tried again just to see if it works and I didn't had crash this time. So I'm not sure either why it did that.
At first I though it was something from my side so I was not sure at to post it as an issue, it seems to be the case.

Anyway, I will try a few times to be sure.

As for your questions:

- I mainly use Chrome but I have Firefox and Opera as well that I use from time to time (at the time of the crash it was Chrome). I mainly copied from Chrome if I remember correctly, I just tried this time with Sublime Text but the link is not detected and it works with Discord. As for the extensions/plugins I've got a few so...
- I don't have my Windows istelf virtualized but the option is enabled. Not sure If I had some virtualization or emulation tool open at that time, but I don't think so.
- Hard to say here, I've got some stuff, for the virtualization probably the default ones when you enable it.
- I use an english version of Windows with a french AZERTY keyboard.

Note: custom domains does not work, I copied one or two of them but I doubt it causes the crashes as subdomains were making them too (the crashes).

**Comment by johanneszab** [comment]
> Note: custom domains does not work, I copied one or two of them but I doubt it causes the crashes as subdomains were making them too (the crashes).

Yes, there is a workaround explained in #21. It would be possible to implement the grabbing of the original tumblr.com address from the custom domains, but someone has to write the code for that.

**Comment by Dexyne** [comment]
That's what I though for custom domains.

Otherwise I tested it again but yet understand why it does that. I launch the program and use the clipboard option almost right away (or maybe after one manual addition). The crash append once or twice then it stopped, even with the option on (though I deactivated it a bit after some tests cause it's not really a fun thing to have when you simply want to add a few blogs xD ).
During and after the crash I didn't change much with the open programs. And I did my copying from chrome.

So, again, I'm not sure why it does that, nor how. Sadly :'(
