### ISSUE TITLE
Cannot restore the hidden columns of the grid list

### ISSUE THREAD

**Issue by UltimateGTR** [johanneszab/TumblThree#137]
Once the columns of grid list being toggled hidden, it can't restore by right click from the other headers, they are not exist from the drop down menu.

**Comment by johanneszab** [comment]
You'll have to hide another one that is currently visible, than restore that column, then right click on the just restored column, and then you'll see the missing ones. 

Or delete your settings / the corresponding entry in the settings.json file. 

I don't know where the bug is, and I've already spent way more time in that than I initially wanted, thus I gave up at some point since there were more important things to do.

**Comment by UltimateGTR** [comment]
Thanks for the reply!
Just got back the columns using your workaround!
I agree the adding new features are more important than fixing this one, please allow me to express the appreciate of your work here, this gem should get more attention!

**Comment by johanneszab** [comment]
\o/
