### ISSUE TITLE
Incomplete/corrupt mp4 files.

### ISSUE THREAD

**Issue by keokitsune** [johanneszab/TumblThree#141]
I don’t know if I’m just missing something but so far it seems like an excessive number of downloaded files stop halfway through or when played though a different media player I get a file content is corrupted message. It seems like it’s every other video is affected.

**Comment by johanneszab** [comment]
Lower your parallel connections to smaller than/equal to 8? (maybe 6 or 4)? It depends on your bandwidth too.

I've written more about this here (and onwards): https://github.com/johanneszab/TumblThree/issues/121#issuecomment-326294899

It is a response from the server: _EOF/null byte/unable to read from transport stream_, not a client issue. The tumblr server forcefully close all connections. My guess from my testing is that they kill all open connections if there are too many open in parallel. The more there are open, the earlier they close them. At some settings none seem to get closed at all. They all get closed at the same time too, regardless of when they're opened. I don't know why they'd do this..

Thus, it also depends on your connection bandwidth. The earlier you finish the downloads, the better. And on the stuff you download as images are smaller. But if you only download videos, you might want to lower the settings that it somewhat satifies your bandwidth without getting EOFs from the server.
Thus, the default settings cannot cover all scenarios and you'll have to play to get your desired values.

I've added some kind of mitigation by retring the download if you get one of those specific answers from the server, and you can increase the _MaxNumberOfRetries_ setting in the settings.json, but that only workarounds the problem and my still lead to unfinished downloads. Sure, you probably can set that to 100, but I don't know if that might introduce other issues. I.e., I simply haven't had time to test all this properly

Also If you re-queue/download, the downloader will resume the unfinished files.

Whats your current parallel connection setting set to?

**Comment by keokitsune** [comment]
10 but ill try something like 5

**Comment by johanneszab** [comment]
Maybe it's enough to introduce a separate parallel connection value for videos since they all are hosted on a separate hosts (vtt.tumblr.com) compared to the photo and also audio files. Maybe only those hosts send the EOF in the middle of the download. That would allow us to set the video downloads to 4 and photos to 10 or some thoroughly tested values..

Browsers probably don't have this problem since they usually only download a picture preview of the video and buffer one video at a time ..

But I personally don't have time to this right now. I actually though of migrate the whole download code from _[WebRequests](https://msdn.microsoft.com/en-us/library/system.net.webrequest(v=vs.110).aspx)_ to _[HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx)_ at first since the webrequests stall if the connection has issues as they don't have a timeout if they are used asynchronously.

So, If someone is interested in this, feel free to play around.

**Comment by johanneszab** [comment]
Okay, please test the v1.0.8.23 version if this helps. I've quickly hacked a separate counter for video connections into TumblThree..
Maybe it's possible to set the value for downloading videos to something like 4, but the total download to 8 (or above). Then you'd download 4 videos and 4 photos at a time, or 2 videos and 6 photos at a time, but never more than 4 videos..

My connection is rather crappy for downloading a huge amount of videos and I usually only download small blogs for testing, otherwise everything would take even longer.

Hopefully only the video hosts sends those _EOF_ messages.

**Comment by johanneszab** [comment]
With the limit of connections to the vt.tumblr.com host and the improved timeout, I think this is finally fixed and I'll close this issue.

You can still reopen it in case it's not.
