### ISSUE TITLE
Option not to re-download deleted, renamed or moved files that were downloaded from the Tumblr search and tagged pages

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#142]
Hello, Johannes. 
I noticed that the program seems to be ignoring or simply not using such a file-lists like * _files.tumblrtagsearch and * _files.tumblrsearch that are stored in Index folders, because when after end of crawling I use a duplicate search program to delete all duplicate images and the next day I run a new crawling to download new images added after the last crawl, then the program still continues to re-download deleted files. With regular blogs there is no such problem, the program does not download deleted files if index files are stored, which is very convenient for me. But this option does not apply to new functions of downloading images by tags and search keywords. I would like it to be implemented for these functions too. Thanks!

**Comment by johanneszab** [comment]
Can you append two pairs of blog files (so the _files and the non _files) of searches where that has actually happend? If they are too large, you can also send them to me via email.

In principle it shouldn't work different as for blog downloads since the downloader code is the exact same, just the scanning/detection of photos/videos is different. But I haven't have time to check it thoroughly though.

I probably also won't have time to fix anything, if it's in case broken, before next weekend.

**Comment by Taranchuk** [comment]
Of course, here is the whole Index folder.
[Index.zip](https://github.com/johanneszab/TumblThree/files/1313544/Index.zip)

**Comment by johanneszab** [comment]
When I do a tumblr search, delete all the downloaded files (i.e. photos and videos) afterwards and re-queue the search, no (new) files are re-downloaded.

In your _files database is no duplicate either, so in principle it does work as it works for blogs. There is also no filename with a smaller image size of the same file in the _files database.

Thus, I think it works. For testing it more thoroughly I probably won't have time.

**Comment by johanneszab** [comment]
Did you actually fix your connection issues?

Do you still have to regularly kill TumblThree? If the download does not completely finish, TumblThree will not update the databases on the disk. Thus, if there is a stalled connection because of wonky wifi/internet and you remove duplicates between different blogs, the same files might be re-downloaded.

Since I've told you this already at least 4 times, I really hope it's not the same issue again.

**Comment by Taranchuk** [comment]
> If the download does not completely finish, TumblThree will not update the databases on the disk. Thus, if there is a stalled connection because of wonky wifi/internet and you remove duplicates between different blogs, the same files might be re-downloaded.

Yes, it seems that case. I've been testing more, on small searches with several hundred images. When the download completely completes and I delete the files, then the program does not download the deleted files. On large searches, it happens to me that the download stops or when the download is finished and I close the program, then the process still exists in the memory and I have to manually end it so the index files are not updated too. So the problem is on my side. Sorry for bothering you.

**Comment by johanneszab** [comment]
Possible duplicate of #116.
