### ISSUE TITLE
Hidden Tumblr doesn't download

### ISSUE THREAD

**Issue by Kakashi82** [johanneszab/TumblThree#145]
I Log me in With the Authentification. Sry for Bad English.
but the Loader dont load any Pics of this URL.

**Comment by johanneszab** [comment]
Two things:

1) could you retry the download with the [newest release](https://github.com/johanneszab/TumblThree/releases/download/v1.0.8.24/TumblThree-v1.0.8.24.zip)? I've silently updated it three days ago because someone else posted the same [on my website](https://www.jzab.de/comment/3907#comment-3907), and if you've downloaded TumblThree earlier or somewhere else, it might already have been fixed.
2) Please post the blogs url otherwise I cannot fix it if it's still broken.

**Comment by Kakashi82** [comment]
Have download past 3 hours Version 1.0.8.24 the newest

Am 29.09.2017 09:04 schrieb Johannes Meyer zum Alten Borgloh <notifications@github.com>:

Two things:

  1.  could you retry the download with the newest release<https://github.com/johanneszab/TumblThree/releases/download/v1.0.8.24/TumblThree-v1.0.8.24.zip>? I've silently updated it three days ago because someone else posted the same on my website<https://www.jzab.de/comment/3907#comment-3907>, and if you've downloaded TumblThree earlier or somewhere else, it might already have been fixed.
  2.  Please post the blogs url otherwise I cannot fix it if it's still broken.

**Comment by Kakashi82** [comment]
Können auch Deutsch reden wenn du Deutsch kannst laut deinem Namen :d

**Comment by johanneszab** [comment]
You didn't answer my second point. I still need the url/name of the blog, otherwise I cannot reproduce the error. If I cannot reproduce the error, I cannot fix the code, thus having created this issue is kinda senseless.

I don't even have time to keep up with the development and fixing the all the issues that stack up here. Thus I certainly won't start now and download several hundreds of blogs to check if the code indeed does not work for downloading all of the hidden tumblrs since I'm sure TumblThree does indeed download (some) hidden blogs.

In essence, always state what exactly you did to trigger the issue.

**Comment by Kakashi82** [comment]
https://illegalbeautyus.tumblr.com/

Can it be that the user is deleted or all is deleted ?

**Comment by Kakashi82** [comment]
app do now if i add with clipboard 3 or more posts, no reactions and quit

**Comment by Taranchuk** [comment]
Kakashi82, this is not a hidden blog, but an offline (deleted) blog, which means that it's impossible to download anything from it. In new versions they are for some reason called hidden and they are not marked in red, this probably led you astray.

**Comment by Kakashi82** [comment]
Ah ok I understand

Am 02.10.2017 08:20 schrieb Taranchuk <notifications@github.com>:

Kakashi82, this is not a hidden blog, but an offline (deleted) blog, which means that it's impossible to download anything from it. In new versions they are for some reason called hidden and they are not marked in red, this probably led you astray.
