### ISSUE TITLE
Doesn't actually launch a visible window [Win 10]

### ISSUE THREAD

**Issue by imglib-sinnae** [johanneszab/TumblThree#150]
I've uninstalled, reinstalled, on two separate unlinked machines. After launching and working properly the first time, it now only shows as an active application in the toolbar, but hovering over the icon shows a preview of a window with stop/start buttons, but there is no actual application window I can find. It simply does not appear. Any insight into this? I've resorted to using TumblTwo but it splits up the index and as far as I can tell they don't share .tumblr formats in the slightest.

**Comment by johanneszab** [comment]
Well, it does launch for me, and several other people here too. So, I don't know, it's the first time I've heard of it and I cannot help without more information. It's probably specific to your installations otherwise someone would have brought up that earlier. 

You could check your Windows Event Viewer and see if there is something in, but I doubt it.
