### ISSUE TITLE
Program doesnt download inline images?

### ISSUE THREAD

**Issue by blezinski** [johanneszab/TumblThree#16]
Is it supposed to or not?

**Comment by johanneszab** [comment]
No it's not. I actually didn't know you can do this until now.

It's easy to get them though. I'm working on a website parser right now to allow downloads of blogs requiring a previous login and to allow downloads of tagged posts from the whole tumblr site instead of from just a single blog. I'm not sure if I'm going to add the inline image downloads right now or after I've finished the parser.

**Comment by blezinski** [comment]
thanks for the quick reply mate, simply wondered whether the program didnt do it or i had just lost my mind

**Comment by Taranchuk** [comment]
> I'm working on a website parser right now to allow downloads of blogs requiring a previous login and to allow downloads of tagged posts from the whole tumblr site instead of from just a single blog. 

This is great news. Would be desirable, if a web parser will also download posts by keywords in captions. Thank you for the development of this wonderful program!
