### ISSUE TITLE
Could not restore UI settings

### ISSUE THREAD

**Issue by reyaz006** [johanneszab/TumblThree#167]
This is the error I always get when the application is launched.

Additionally:
- every time I close the application, it crashes, losing all saved settings.
- if I press Pause while the queue is being processed, the application freezes.

I'm not sure if these deserve separate reports, at least until the UI error is solved.

**Comment by johanneszab** [comment]
You'll have to delete your settings in C:\Users\Username\AppData\Local\TumblThree\Settings\ since you apparently upgraded from some previous version. No settings/queue will be updated/saved until you've resolved this.

I'm sure it's written and explained in a older release where I've changed the settings and there are also some old issues about this.

**Comment by reyaz006** [comment]
I don't have that folder neither in %localappdata% nor in %appdata%

Settings files are being saved in the application folder.

**Comment by johanneszab** [comment]
> Settings files are being saved in the application folder.

Then obviously delete your local settings in the application folder. Be sure that there are no global settings in %localappdata% either and that TumblThree is off while you delete the settings.
