### ISSUE TITLE
[Feature test] Test Imgur, Gfycat and Webmshare externally hosted file support

### ISSUE THREAD

**Issue by johanneszab** [johanneszab/TumblThree#169]
I'd like someone to test if the new support for downloading Imgur.com, Gfycat.com and Webmshare.com linked files within tumblr posts does affect the stability of TumblThree. In particular, does it stall or crash the application or miss files that are externally hosted on any of those three hosters?

Thanks!

[TumblThree-v1.0.8.30-Application.zip](https://github.com/johanneszab/TumblThree/files/1468416/TumblThree-v1.0.8.30-Application.zip)

**Comment by Taranchuk** [comment]
Thank you for introducing new features into the program!

Tested at http://coppermailman.tumblr.com, where there are imgur links in the posts and all of them seem to download normally. But I also noticed that video files were not downloaded, although judging by the information from the blog setting, they had to download in the amount of 111 items. With the exception of this bug, the program itself behaves normally, without freezes and crashes. 

I did not test Gfycat and Webmshare though, because I have not yet met blogs that publish content from these sites, but if I meet them, then I'll check the behavior of the program on them and write about it.

**Comment by johanneszab** [comment]
Thanks!

I've only added picture support for imgur since I didn't know/checked at all what kind of files you can upload there. Adding video support should only be a couple of additional lines.

Thanks for the information!

**Comment by Taranchuk** [comment]
> I've only added picture support for imgur since I didn't know/checked at all what kind of files you can upload there. 

No, I was talking about tumblr hosted video, or rather, during the writing of the comment, I thought they were them. I now downloaded video metadata file and it looks like all the mentioned videos from vid.me, not from tumblr.com and I also checked several links in the browser and it seems that these videos are removed by the request of copyright. So this is not a bug, I apologize for the false alarm.

**Comment by Taranchuk** [comment]
I found this blog http://diejetty.tumblr.com, judging by the metadata files, there must be at least more than 60 links from Gfycat and they seem to have all been downloaded to the folder (I see that there are more than 60 such files). All in mp4 format and they are successfully played in the video player. And the download process went smoothly and without problems. So for me, the function of downloading external files works successfully. This is a really good addition to the program, it is very good to be able to download additional files from blogs. Thanks for updates!

**Comment by johanneszab** [comment]
Thanks, I still did some minor changes and will probably release a new version this weekend including these changes.
