### ISSUE TITLE
Downloading specified higher resolution pictures often/always leads to same image

### ISSUE THREAD

**Issue by Jalbre2** [johanneszab/TumblThree#17]
I doubt that TumblThree is the issue here, instead it's Tumblr's file naming or api, but anyway, I ran through my blogs again today. I ended up with 43,000ish files. I ran those files through dupeguru, both against themselves, and then against my reference files from older downloads. That lead to deleting 8000 photos, and 23,000 photos, respectively. For the second run, dupeguru showed that files with the exact same filename except for the end(_400 vs _1280, for example) were exact duplicate files. Here is a screenshot: https://imgur.com/RTqQlQB

I have not had a chance yet to check whether this does sometimes result in your intended(and super awesome!) idea. Perhaps I'll use a mass renamer on both sets of files to clip off the end of the filename and see if there are still collisions based on filename but with different file sizes.

I don't know if you have considered this, but regardless of the outcome of the above, I think doing duplication checks based on the md5 hash rather than the filename can address all of the above. Also, if my wording before wasn't clear, what I mean by "against themselves" is that dupeguru found that different blogs had downloaded the same exact images today that had different filenames. This has always been the case, and isn't too big of a deal for me thanks to Dupeguru, but I figured I would mention it as well.

**Comment by johanneszab** [comment]
> I don't know if you have considered this, but regardless of the outcome of the above, I think doing duplication checks based on the md5 hash rather than the filename can address all of the above. 

I know, but for doing this you'd have to first download the file otherwise you cannot get the md5 hash. That's why I've never considered this. I actually wanted to save the network bandwidth not the disk space. During the TumblTwo development I've thought to implement a global list containing all md5 sums of all downloaded files from all blogs and compare the downloaded files against it and if they would match to delete the file again. But I thought it's unnecessary. DupeGuru can probably do that better anyways. I'm not sure, it's still possible to do for those people who might want to have each file just once.

And for the larger files option, yeah, it will downloaded the file twice if the filename including the size after the dash differs. It's probably worth to implement it to just save the name without any suffix (e.g. tumblr_o7p5ei4iGh7qjlsrio1), excluding the files extension and the pixel size, but for that, I'd have to write a database updater first. That's why I've not done it. So the best it do either enable it for new blogs only, or just leave it off. I doubt there will be too many files where is resolution is actually better.

**Comment by Jalbre2** [comment]
Alright, great. Thanks for the clarification!
