### ISSUE TITLE
Tubmblethree keeps saying "Limit Exceeded"

### ISSUE THREAD

**Issue by Linktydraa** [johanneszab/TumblThree#170]
Hi Johannes,

I keep getting the error message that the tumblethree "Limit exceeded" when downloading the blogs.

I have the "Concurrent Connections" setting set at 54. It was at 100 before I received the error.
I have the "Concurrent Blogs" Set at 7. That number is the same.
I have the "Scan Connections" Set at 50. It was 90 before.

I am using Version 1.0.5.54

**Comment by johanneszab** [comment]
You are probably downloading a hidden blog (that requires a login)? Use one of the other versions (i.e. _not_ the 1.0.5.X branch) since the release you're using doesn't contain a rate limiter.

I'm not actively testing all the branches, only the main branch (v1.0.8) and I am only back porting all my changes to the other ones in case someone finds interest/time in the other branches to improve them. You cannot download hidden blogs without login anyways, thus it probably makes no sense to have it in the v1.0.5 release which I originally created to have a "all anonymous/login free/api free"-release.
