### ISSUE TITLE
TumblThree crash after adding 500+ blogs from the clipboard.

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#18]
When I copy from the text editor a list of 500+ blogs, TumblThree begins to add them to the blog manager, but program crashed after 3-5 seconds. Could you fix this?

**Comment by johanneszab** [comment]
Please send me the list per mail then I'll take a look. Maybe it's a specific blog in that list, and I'm not trying to figure that out on my own nor do I think I'll collect 500 blogs.

**Comment by Taranchuk** [comment]
Well, I sent. In fact, the list of more than 9000 blogs and crash happening after copying the first 500 blogs. When I copy 250 blogs and then after 5-10 second copy the another 250 blogs, the program does not crash and all blogs correctly adding to blog manager.

**Comment by johanneszab** [comment]
Ok, I've fixed it, but some of the newly added blogs will still appear as offline, even if they probably aren't since the tumblr.com network isn't responding to some of the connections you are opening to them. That's actually why the crash happens. I've also not thought that in this particular function the connection could be refused from the remote side because of too many open sockets.

I'll release a new version including this fix in a few days with some network enhancements for improved speed and proxy support.

**Comment by Taranchuk** [comment]
Thanks you for the solution of the problem.

**Comment by Taranchuk** [comment]
With version 1.0.4.14 program still crash when adding 500+ blogs. But if earlier a program crash during the addition of 500+ blogs then now crash occurs through 30-45 seconds after adding all the blogs to program. First 500+ blogs are added correctly, but when after crash I re-entering the program and add other blogs from list, regardless of their number (50 blogs or 500 blogs), crash occurs again and not all new blogs are added.

**Comment by Taranchuk** [comment]
Any solution? The situation has not improved with the version 1.0.4.15.

**Comment by johanneszab** [comment]
It's crashing now in a deadlock of the user interface (ui) because there are to many entries for the Dispatcher to work off. Every blog your add starts a new task in the background and once it collected all data it wants to update the ui to add a new row in the blog manager, but they are not limited in anyway. So they probably all hit roughly at the same time.

I haven't come up with a solution yet that I like. There are some with limiting the work for the dispatcher or add things directly from the ui, but I don't like them.

**Comment by Taranchuk** [comment]
I do not know what happened, but from today on crash occur during the addition of 500+ blogs, but not after 35-40 seconds after the addition of all blogs. When I re-entering the program after crash I see that not all blogs have been added, but only part, somewhere around 220-250 blogs.
I have a suggestion. When I add 500+ blogs I mainly use it to extract meta-data from these blogs. Maybe it makes sense to introduce an optimized mode for only extracting meta-data, where new blogs will not collect information for the user interface and so will not occur crash?
