### ISSUE TITLE
Authentication seems to have no effect for crawling after a successful log in

### ISSUE THREAD

**Issue by easonyzwang** [johanneszab/TumblThree#180]
I use the link：https://www.tumblr.com/liked/by/foobar
add blog, then add to queue, then crawl.
But there is always a error:
**Error 1: You need to login to tumblr.com for downloading foobar. Go to settings -> authenticate.**
But after I finish authentication, the error 1 appeared again, and I have to authenticate again, and the error again... infinite loop.
How to fix it?

**Comment by johanneszab** [comment]
I don't know, since this has never happened to me, thus all I can do is guessing. Could you elaborate more on your system, and what steps you did to trigger this behavior? Windows version, any antivirus/security software that might block access to the Internet Explorer cookies?! Do you use the Internet Explorer for browsing?

Here is some one with the same symptom. He delete the cache/cookie within the Internet Explorer (settings wheel -> Internet Options -> Browsing History -> Delete), re-authenticated and it worked afterwards:
https://github.com/johanneszab/TumblThree/issues/171#issuecomment-345447059

I'd really love to improve the code if there is something wrong, but based on your description, there is nothing I could possibly do.

**Comment by thaindq** [comment]
@johanneszab I was having the same problem and clearing IE cache worked for me. But now I encounter another one. The program just downloads some images and then stop. I have to `Add to queue` again for it to continue but after a few times, it just says `Evaluated x tumblr blog site` and stop. No more images getting downloaded. `Download url list` doesn't seem to work either.

**Comment by johanneszab** [comment]
I'm again just guessing, and without seeing it for myself, I cannot really do much.

If that is happening during downloading liked/by posts, then set the settings back to defaults. I.e. not one connection, also not too many. Something like 5-10, but increase the time out option. 

For me it sounds like the crawler connection dies and stalls the application. Crawling likes couldn't be usefully parallelized since there was no was of way of telling the maximum time span of the liked/by posts beforehand. And since every new page contains a time stamp that is embedded in the previous page, the scanning serial.
I haven't checked what would happen if that thread dies, but since you could always download a few more posts, that somehow sounds like it. As written in the description l the code for notification of those events is still missing, and my connection here is rather quick and stable.

Like I've mention in all other threads here before: Include the URL you want to download, otherwise I cannot look into it. And if you share the url, how many posts did it download for you? Another thing you should do is to always test everything with the defaults again before opening a new issue.

But thanks already for the detailed description and giving some insights to the previous question.

**Comment by johanneszab** [comment]
I've browsed until I've found 3 blogs random blogs where I could access the liked/by site. For me, there is no issue. Default settings, simple added the sites and click on crawl:

![tumblthree_likedby_downloads2](https://user-images.githubusercontent.com/1684561/33795839-3773517c-dce9-11e7-87d9-a6652a91014c.png)

Until I get a web site (or even better, sample photo or video posts) were a large amount of downloads is missing, I assume that there is no issue.
