### ISSUE TITLE
[Request] [Enhancement] Option for JSON output

### ISSUE THREAD

**Issue by nevercast** [johanneszab/TumblThree#187]
Hello,

Currently `Blogs/blogname/` contains `images.txt`, `quotes.txt` and the like. Their format is easy to understand but has poor parsability, and can be broken with some malformed text input since there is no escaping or quotation in the values of the key-value pair.

Since `Blogs/Index/*` already uses JSON as it's format, I'd like to see the metadata move towards JSON as well. This would allow me to rebuild the blog from the dump.

I also think it would be good to move towards JSON as a default by the next major release, but offer the option of txt/json until the next major update (as some other users may already depend on the txt based key-value pair).

Cheers,
NC.

**Comment by Taranchuk** [comment]
There is already metadata in the format json. Just enable the "Dump crawler data" during downloading the blog.

**Comment by johanneszab** [comment]
> There is already metadata in the format json. Just enable the "Dump crawler data" during downloading the blog.

That's only true if you use the svc version (v1.0.7.X branch), since the master branch (v.1.0.8.X) uses the api v1 which data is in xml. Except if you download hidden blogs, then both versions use the the web service (SVC) that displays the regular webpage.

Thanks for suggestion. Actually, I've wanted to refactor the text parsing at some point. It's one of the last parts of the application logic I haven't toched for a longer time and it doesn't fit in the classes it's right now. Thus, after that I can also add an additional output form as json next to the already implemented plain text (.txt).

**Comment by nevercast** [comment]
I'll try the "Dump crawler data" option in the interim. Thanks for seeing to this issue.

Cheers

**Comment by johanneszab** [comment]
I've changed the master branch to dump json instead of xml as well. For this, I've change the code that handles the tumblr api data. It's more clean and internally uses its own class now instead of XDocuments. Thus, there might still be some bugs: 

[TumblThree-v1.0.8.36json-Application.zip](https://github.com/johanneszab/TumblThree/files/1606884/TumblThree-v1.0.8.36json-Application.zip)

I know it's not what you've asked, but with this in the code, it's probably just a few lines to add a json metadata parser that equivalent to the current one (basically strip things we don't want from the api requests).

**Comment by Taranchuk** [comment]
I downloaded the new version and blogs do not even download at all, they remain blue and nothing else happens. With dump crawler data or without (just download images), blogs remain stall. In addition, all changes to the settings are lost after the closure of the program.

**Comment by johanneszab** [comment]
> I downloaded the new version and blogs do not even download at all

No issues for me.

**Comment by Taranchuk** [comment]
Hello, Johannes. I downloaded the new version (v1.0.8.37) and blogs were not downloaded again. These were blogs that I added manually. But when I copied the index files from the previous version and ran the program, it turned out that these blogs are downloaded normally with any download mode (metadada or images). Blogs manually added cannot be downloaded at all. So maybe there is a problem at the stage of creating a new index of files when I manually add blogs. Here I attach the index files from two blogs, you can import them and see if you have a problem. 
http://hjkma.tumblr.com - this is my small blog that I added manually and which does not download at all.
http://your-canuck-specter.tumblr.com - this is a blog imported from the previous version and which is downloaded normally in the new version.
[Index.zip](https://github.com/johanneszab/TumblThree/files/1609068/Index.zip)

Also I can write my PC's specifications if it's necessary.

**Comment by Taranchuk** [comment]
Sorry, I misunderstood the problem. Now I manually added your-canuck-specter blog to the program and it turned out that it normally downloaded. I also added several other blogs and they also download normally. The thing is the program can not download only some blogs, that's the reason. 
hjkma blog is among these blogs that do not download at all. Now I have uploaded a large list of blogs to the program and after completing a crawl I will give a list of all the blogs that are not downloaded.

**Comment by johanneszab** [comment]
Yep, you were actually right. Blogs with <50 posts didn't work. 

I've actually had a logic error in the code, but it must have been there for a long time. It was just differently handled. The previous code using the xdocument/xml from the api just returned a zero instead of a null exception.

It should be fixed now, I've updated all releases.

Thanks for posting the examples above.

**Comment by Taranchuk** [comment]
Yes, I downloaded the latest version, the hjkma blog now is downloading normally. Thank you! But still there are blogs that I can not download. For example, this blog https://420powell.tumblr.com/ continues to be stall and does not go to downloading. Could you check this?
Tomorrow I will test the entire my list of blogs and I will post here the address of non-working blogs.

**Comment by Taranchuk** [comment]
Yes, I downloaded the latest version, the hjkma blog now is downloading normally. Thank you! But still there are blogs that I can not download. For example, this blog https://420powell.tumblr.com/ continues to be stall and does not go to downloading. The download settings were "download images", "download reblogged posts" and "download specific size". And again after the restart all changes in the settings are reset and all download settings are reset too, all the checkboxes are unchecked. And after I mark all the necessary download checkboxes and start crawling, this blog does not download anyway.
Could you check this out?
Tomorrow I will test the entire list of blogs and I will post here the address of non-working blogs.

**Comment by johanneszab** [comment]
Thanks, fixed.

I've also found another issue with the serialization trying randomly 200 blogs of your list. If you find any more issues, let met know.

So, whats still missing for the json parsing is that someone has to unify the json outputs from the regular (api) and hidden (svc) requests.

**Comment by Taranchuk** [comment]
I have not finished the crawling yet, since 2800 blogs have reached 100. But I found two non-working blogs.
https://hay.tumblr.com/
https://selfpics.tumblr.com/

**Comment by Taranchuk** [comment]
Here's a blog
https://selfpics.tumblr.com/
when I manually add it to the program for the first time and place it in the queue panel and start downloading while all download checkboxes are marked, nothing happens. After restart, all settings are reset, but this time after checking only the image download mode, the blog is already downloaded normally. Here something is probably wrong with the download modes. Text posts and metadata are not downloaded here at all. Images are downloaded normally. When all checkboxes are marked, the download stalls.

**Comment by johanneszab** [comment]
Thanks. Should be fixed.

Should have stayed with the xml crap..

**Comment by Taranchuk** [comment]
OK. I also want to say that on hidden blogs does not work the function of downloading posts by the pages, when I set the number for example 1-3 last pages for downloading, then the program downloads blogs completely, not just the last 3 pages. Also when the downloading of the hidden blogs ends and I put them in the queue panel again, then the program starts to scan them completely from the beginning to the end and does not crawling only the last posts (for example 250 last posts, since this works with regular blogs). It would be great if you could fix it.

**Comment by nevercast** [comment]
This should probably be posted as another issue, if it persists it will be difficult for other users to find the issue in these comments.

**Comment by Taranchuk** [comment]
Yes, you are right. If other users do not find a description of this problem here, then they can create a topic about this bug and will thus be a duplicate issue that the developer has already seen. I deleted my comment and created another topic. My apologies for the offtopic.

**Comment by nevercast** [comment]
Is this now implemented?

**Comment by johanneszab** [comment]
I think I did that already weeks ago, ..

https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.39
https://github.com/johanneszab/TumblThree/commit/196df7378d4b1d43cb90f9cb26b55b9025cbebd2
https://github.com/johanneszab/TumblThree/commit/bbc21813a3140de271f3300835fd22e8a417ba26

**Comment by nevercast** [comment]
Missed that. Thanks
