### ISSUE TITLE
Hidden Tumblr not working if reblog option unchecked.

### ISSUE THREAD

**Issue by bun-dev** [johanneszab/TumblThree#194]
Hello,
I'm not sure what I'm doing wrong, but I can't seem to get hidden tumblr blogs working.(The ones that only display from your dashboard). Steps I have taken include:
1. authenticating via the button 
2. Re-downloading IE and making sure the tumblr cookie exists
3. Using the blog url instead of 'tumblr.com'.

![screenshot 8](https://user-images.githubusercontent.com/34141271/34797950-14ab1ca8-f628-11e7-9861-65385f7ff1c2.png)

When I crawl it, it says 'evaluating x blog sites', then stops with nothing downloaded. Here is the url used:
[https://www.tumblr.com/dashboard/blog/wabutt](url)

If I'm doing something wrong please let me know, thanks!

**Comment by johanneszab** [comment]
The blog works in TumblThree for me (default settings), so the issue is probably on your side:

![wabutt](https://user-images.githubusercontent.com/1684561/34799562-8e8debee-f660-11e7-8fa4-2682c3dc90ec.png)

Since it states "evaluated x tumblr blog sites", I'm guessing it's actually doing its job, but you probably forgot to check _Download reblogged posts_. I think It's as simple as that (or you didn't check anything to download, or you specified in invalid blog-wise download location).

Could you also share the same screenshot with the details view open?

**Comment by bun-dev** [comment]
> you probably forgot to check Download reblogged posts.
Thanks! I didn't realize that had to be checked since it downloaded from the other tumblrs just fine. It's working fine now

**Comment by johanneszab** [comment]
You should check that checkbox in the other blogs as well if you want to completely download them. Most posts are reblogs in my experience.

**Comment by FatKiwi** [comment]
Not working for me too unfortunately. The blogs I try have original posts, but still the same "evaluating" message and nothing happens.

**Comment by johanneszab** [comment]
blogname/url?

**Comment by FatKiwi** [comment]
I sent you an email with the blogs. Hope you can find the culprit. Thanks

**Comment by johanneszab** [comment]
They all download if you enable the "download reblogged post"-checkbox. For the hidden Tumblr Crawler, it currently downloads nothing if you do not enable that checkbox. Fixing that so that it only downloads reblogs is 7 letters of additional code, but packing the binary, upload and everything is nothing I've currently time for.

Thus, enable the checkbox if you download hidden blogs, or fix the code by yourself, or wait until the next release.

**Comment by johanneszab** [comment]
Thanks for the blog! And making me aware of..

**Comment by FatKiwi** [comment]
No problem for binaries, I can compile it myself if you push commit. At least you found what is wrong, so thank you.

**Comment by johanneszab** [comment]
I _think_ from my brief testing that in [line 485 in the TumblrHiddenCrawler.cs](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs#L485)

it should be:

     if (post.reblogged_from_tumblr_url == null)

instead of:

     if (post.reblogged_from_url == null)

**Comment by johanneszab** [comment]
I've made a [new branch](https://github.com/johanneszab/TumblThree/tree/parser) for the mega and google drive parser as there was still some work to do and I wanted a new release that fixes the proxy issue (#204).

**Comment by FatKiwi** [comment]
Thanks for release 👍
