### ISSUE TITLE
Internal error description / MaxBytesPerSecond has to be <0

### ISSUE THREAD

**Issue by aPassingVisitor** [johanneszab/TumblThree#20]
I like TumblrThree's design better than older versions. And I have gotten it to work a few times.

But...

After a while of use (4 -6 times), on load, the program fails.
It *will* allow you to add tumblrs to the cue, but will not crawl the tumblr sites.

The program only starts working again once I delete the entire program and associated libraries, all the directories containing downloaded flies, and the _AppData\Local\TumblThree\Settings_ files under the User directory. 

Details:

1) You start the program.
2) An error message appears in the top status line (just above the list of tumblr blogs), reading:

    **Error 1:Could not load file in library:**

Highlighting the error message gives you the extra info:

    Internal error description
    MaxBytesPerSecond has to be <0

I have tried lots of work around like adding all the blogs to the cue and then removing them, rebooting, etc.

All that seems to working is deleting every trace of the program and starting over.

**Comment by johanneszab** [comment]
It's probably [> 0](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/ThrottledStream.cs#L23). Something that I've forgot to internationalize.

Can copy and paste the value you've entered in the "Limit Bandwidth (kb/s)" field in the settings window? I've tried to limit the acceptable values by making using a validation rule but it apparently does not work for you. Only integer values from 1 to 2147483647 are allowed there. No dots, no commas.

**Comment by johanneszab** [comment]
Are you sure the error description *MaxBytesPerSecond has to be >0* is from the error *Could not load file in library* and not from a follow up error?

That somehow doesn't make sense since the files actually should load without any internet connection. So maybe it's two issues or something completely different.

Can you send me one of the broken library files (*.tumblr in the Index folder of your download location) the next time this happens?

**Comment by johanneszab** [comment]
Thanks for reporting, I've found.
