### ISSUE TITLE
Last 2 releases crash Windows 10 64bit

### ISSUE THREAD

**Issue by iampilchards** [johanneszab/TumblThree#201]
I have 83 blogs, but only download one at a time.
After a random time of between 1 hour and 2 hours, the program freezes. I have bypassed the anti-virus and firewall for the program, as well as closing all applications besides TumblThree. I still come back in the morning, or later that evening, to find TumblThree frozen and everytime the progam either refuses to close and I'm unable to use and restart my computer unless I do a hard reset. I'm not a fan of hard resets, but I'm a fan of this program.

1.0.8.36
1.0.8.39
Can I attach a log file, and where do I find it?

I will try an earlier release to see if the problem goes away.
Thanks.

**Comment by johanneszab** [comment]
Can you upload your settings file and some of your tumblr indexes? You can also upload them somewhere else (dropbox, onedrive, icloud) if their size is too large.

Otherwise, there are no logs, and I probably cannot help you except for trying to replicate your issue with those files. But I guess it will not work, but it's a try.

For me it runs 3 days in a row without issues. 

So, your description happens with which release exactly? What exactly do you mean with freeze? You get the hourglass/rotating cycle and have to force quit TumblThree? You cannot press anything except for the settings/about, because the controls don't stop/start the crawl? it crashes Windows 10 (title)?!

You might want to try to delete your settings and give that a try. Btw, you don't have to "bypass" antivir or firewall at all. Why should you? At least not Windows Defender, haven't tried any other antivir, but I guess it's not a different situation there.

**Comment by iampilchards** [comment]
I appended .txt to allow files to upload.
At the moment I'm using 1.0.8.39.
I mean that the window stops responding - not even about works; and then (Not Responding) shows in the window title for any application open. With Task Manager open, it shows 0Mbps before I enem touch the TumblThree window. Once I try stop or click anywhere in the TumblThree window, all my programs stop working and my keyboard doesnt respond to Num Lock.

Yes for the hourglass rorating cycle - when I can force quit, then it's a matter of time before anything else starts crashing. 
Without TumblThree open, my computer can run for a week if I render videos, play Skyrim, etc.
If I catch TumblThree just after it stops working, I can open Settings and "Save" them, but those settings are not retained (not sure when they get written to the file).

I'll give the settings deletion a try.
I use Vipre and it kept on closing the program unless I whitelisted it.

BTW: it worked for a day or two and then settings failed to make any changes unless I closed and reopened TumblThree.


[pilchies_files.tumblr.txt](https://github.com/johanneszab/TumblThree/files/1631888/pilchies_files.tumblr.txt)
[Settings.json.txt](https://github.com/johanneszab/TumblThree/files/1631889/Settings.json.txt)
[justsurrender.tumblr.txt](https://github.com/johanneszab/TumblThree/files/1631890/justsurrender.tumblr.txt)
[pilchies.tumblr.txt](https://github.com/johanneszab/TumblThree/files/1631891/pilchies.tumblr.txt)
[skinlatex.tumblr.txt](https://github.com/johanneszab/TumblThree/files/1631892/skinlatex.tumblr.txt)

**Comment by johanneszab** [comment]
>  I use Vipre and it kept on closing the program unless I whitelisted it.

Okay, never heard of it. TumblThree isn't compressed nor obfuscated, so antivir programs shouldn't see any threat in it, except that it isn't digitally signed, but many open source applications aren't. Like I said, not even Microsoft has any problem with it. You can easily reflect it and see the exact same source code that I uploaded here.

> BTW: it worked for a day or two and then settings failed to make any changes unless I closed and reopened TumblThree.

Maybe that's all related, I don't know. Could all come from the antivir, maybe it tries to protect your system by denying TumblThree to write or something. Who knows. That it actually worked for a longer time at the beginning seems to indicate that and that maybe some file is now broken as a result of any of those crashes/antivir issues and TumblThree cannot handle it.
You might want to give it a new try with the latest releases, fresh settings, and completely newly added blogs. For this, it's enough to move the Index folder away, but you can leave your downloaded files in place. Make sure TumblThree is closed when you do it. All your downloaded files that are still in place will be readded to the databases and not redownloaded. But maybe it fixes any of the blogs databases that have an issue that is not properly handled.
You might also try to disable the "check for file existence globally"-option. I've only added it recently, and since I don't use TumblThree myself regularly, and haven't heard much back of it from other people here, maybe it contributes to your issue.

> I mean that the window stops responding - not even about works; and then (Not Responding) shows in the window title for any application open. With Task Manager open, it shows 0Mbps before I enem touch the TumblThree window. Once I try stop or click anywhere in the TumblThree window, all my programs stop working and my keyboard doesnt respond to Num Lock.
> 
>Yes for the hourglass rorating cycle - when I can force quit, then it's a matter of time before anything else starts crashing.
>Without TumblThree open, my computer can run for a week if I render videos, play Skyrim, etc.
If I catch TumblThree just after it stops working, I can open Settings and "Save" them, but those settings are not retained (not sure when they get written to the file).

Okay, that's really odd. That never happened for me. The complete freeze of TumblThree indicates that the gui/main-thread doesn't respond. It's even more weird that TumblThree should be able to kill your whole system as it's written in managed .NET code (C#).

**Comment by johanneszab** [comment]
> I use Vipre and it kept on closing the program unless I whitelisted it.

I've just uploaded the latest release on [virustotal](https://www.virustotal.com/#/file/fb7d429d9a7acffc705468f56f09576e2f82ac4263f1a2e6fe838cd1ed487ff2/detection) and it came out completely clean (0/61). Exactly like I've expected it. They say it has been tested with VIPRE too: Clean

**Comment by johanneszab** [comment]
So, I'm guessing it must be related to your system (and maybe installed software) and not necessarily to TumblThree. Thus, I can not help you troubleshoot this remotely. That's why I think I'll close this at some point in the feature even if your issue isn't resolved and also because it's the first time I've heard of this in 2 years.

You might want to take a look in your Windows Event Viewer and see if there is any additional information available that might help. You can post/upload anything related here.

**Comment by iampilchards** [comment]
Well it’s working now. Been a few days now. Whatever we did worked!
Thanks 😃
