### ISSUE TITLE
Online blog reported as Offline -or- Add URL format?

### ISSUE THREAD

**Issue by lolliffe** [johanneszab/TumblThree#208]
I added a blog, and its first crawl was fine.  Once it finished, it changed to "Offline", and is now always Offline.  When I go to the URL, it is still very alive, but its Online status never changes.  `Check blog online status on startup` does not seem to help this.

Note:  The site reroutes.  That is, if you enter `blogname.tumblr.com`, you can add the blog to TumblThree, and the same in a browser.  If you open the site directly in a browser window, or `Open the site in the web browser`, you would see that it reroutes to `blogname.me`   I was able to add the blog using the `name.tumblr.com` format, but TumblThree does not accept the old `name.me` format.

**Comment by johanneszab** [comment]
Could you simply remove the blog and re-add -- it in case of you haven't removed or moved any of the downloaded files yet? Otherwise you might want to change the online status manually, similar to what I've explained [here](https://github.com/johanneszab/TumblThree/issues/21) but this time you have to search for _Online_. But actually the mentioned `Check blog online status on startup`-option should exactly do that for you.

Several months ago downloading such non-tumblr.com sites was at least possible [without any issues](https://github.com/johanneszab/TumblThree/issues/21).

I'll shortly check if it still works for me with the blog mentioned in #21.

**Comment by keokitsune** [comment]
in your index folder if you remove the non _file ..file it will remove the blog from the crawler list, manually re add the blog to the crawler. the next time you crawl the blog it will only download files you didnt download the last time.
