### ISSUE TITLE
[Error] A connection timeout occured during downloading of <blog name>.

### ISSUE THREAD

**Issue by AriinPHD** [johanneszab/TumblThree#214]
`Error #: A connection timeout occured during downloading of <blog name>.
"The operation has timed out."`

I've seen this error a few times appear during the testing of the latest version ('1.0.8.41'). Is this a normal error? What happens when this error occurs? Does this skip a post, or will TumblThree attempt to re-download it in the next attempt?

Tested with the following settings on 12 blogs (mix of visible and Hidden; both visible and Hidden have seen this error):
**-- General --**
Authenticated = Yes
- [x] Preview
- [x] Check online status 
- [x] Delete only index
- [x] Remove index after crawl
- [x] Portable mode
- [x] Display confirmation dialogs
- [ ] Check global file existence
- [ ] Start download at ... hh:mm:ss

**-- Connection --**
Concurrent connections = 8 (increased from default)
Concurrent video conn = 4
Concurrent blogs = 2
Image size = Raw
Video size = 1080
- [ ] Limit scan bandwidth
- [x] Limit API connections = 70 per 60 seconds (Reduced from default)
Timeout = 20 (decreased from default)
Scan connections = 8 (increased from default)
Limit bandwidth = 0
(No proxy settings)

**-- BLOG --**
- [x] Download images
- [x] ... Videos
- [x] ... Audio
- [x] ... Reblogged
- [ ] Everything else unchecked/default
Download pages = 1-25 where each page contains 50 posts (default)

**--External--**
All options enabled; drop-down = default.

My network has been uninterrupted, high external bandwidth, wireless internal connection. Windows 10 machine. I'm definitely seeing a good reason for issue #128 (Logging window) which could possibly give more detailed information on issues and errors... :)

**Comment by johanneszab** [comment]
The error message states that there was a download of a file which didn't finish within 20 seconds. Especially if you download multiple larger files (videos), that's not a large amount of time. I also don't know if Tumblr limits the bandwidth at all since my connection is rather crappy and I've never tested it with downloading many videos in parallel, say 4.

The timeout is kinda awkwardly implemented, but the timeout property in the WebRequest api doesn't work for async code which I've only discovered after coding everything. Instead they made the newer HttpClient, but I haven't had time to port the code over to this api yet.
TumblThree is mostly async, thus it runs many things in the background and concurrently without taking an extra (system) threads (resources) for basically waiting (for a download to complete). 

So, whenever TumblThree opens a request for downloading a file or fetching a web page, it has the amount of time you specify there (20 seconds) to complete it, regardless of it's state. Thus, even if a connection is actively downloading something, it will be closed after 20 seconds. But also stalled connections will be closed after 20 seconds. The latter is of course the purpose for this implementation. If you would code this properly, it detects if a connection is stalled and only then begins to count the timeout. This is how it's implemented in the HttpClient. 

So, if you have no general problems with your connection, increase the timeout.

**Comment by Hrxn** [comment]
Wait, do I get this right?
> So, whenever TumblThree opens a request for downloading a file or fetching a web page, it has the amount of time you specify there (20 seconds) to complete it, regardless of it's state. 

This means that, just for example, I am downloading a rather long/big video file hosted on Tumblr (It's the exception, I know, but it occurs), and after 20 seconds the download will be cancelled no matter what, leaving a incomplete/broken file behind?

**Comment by AriinPHD** [comment]
I see! I've completely misunderstood that option. Perhaps it can be worded differently to reflect what it actually does (as it has nothing to do with timeouts) ?

I'll adjust my options in any case and see if errors go away. Thanks, @johanneszab! :)

**Comment by johanneszab** [comment]
> This means that, just for example, I am downloading a rather long/big video file hosted on Tumblr (It's the exception, I know, but it occurs), and after 20 seconds the download will be cancelled no matter what, leaving an incomplete/broken file behind?

Pretty much if you set the connection timeout value to 20 instead of 600 (default). That's why there is the notification. It was either this, or no timeout at all for people with a wonky internet connection. I've never noticed issues for myself, but for those people, the crawl just never finished as soon as a connection stalled.

Thus, for a quick hack, I've added that timeout. As I've said, if the [C# documentation](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.110).aspx) would have stated more clearly that the timeout property is useless when using it asyc -- and not in a subordinate clause -- I'd have directly implemented all the connection code using [HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx).

So, if someone wants something to code, there is plenty of things to do.

**Comment by Hrxn** [comment]
Well, if you get notifications you can do something about it, increase timeouts, whatever.

As long as something like this does not fail silently...

**Comment by johanneszab** [comment]
Ok, I think I've figured out a way on how to timeout only (small) requests like getting webpages and how to timeout chunks of a download i.e. not the whole file itself but check if actually something still arrives over the connection by checking small portions of it.

I'll test this over the weekend and let you guys know in case of the timeout value somewhat changes it's meaning.
