### ISSUE TITLE
Wont crawl......does nothing

### ISSUE THREAD

**Issue by JustVisting** [johanneszab/TumblThree#216]
Windows 10.....

So I have tried running it as admin and disabling firewall but it just does nothing other than show me the number of downloads. 

I have tried previous versions. None work for me. Any ideas?

**Comment by johanneszab** [comment]
> Any ideas?

Yes, read the text on the [main site](https://github.com/johanneszab/TumblThree), and say what exactly you didn't understand. I've written this exactly for the reason so that I don't have to answer/support threads in the kind of "how to use the application, ..". Especially as this is a development place, not a support forum.

Since it states the number of downloads, I'm rather sure it actually works.

Posts screenshots (best), or answer the following:

* did you queue the blog for download at all?
* Is there a green/blue bar in the queue next to the blog if you after you've started the download?
* Do you use a proxy? If yes -> You'll need the latest version.
* What kind of posts did you select for download?
* Did you select `Download reblogged posts`?
* What does does the queue information text say during the download of the blog.

You should be able to answer all of these by reading the main text and viewing its screenshot.

**Comment by bill-ea** [comment]
I have the issue using windows 10 if I try to save new blogs due to shutting down TumblThree (for reboot or shutdown) and then attempt to queue and download at a later time since the "Number of Downloads" column will not have the original crawled number any longer. This has been occurring since TumblThree-v1.0.8.32 or so, The issue I have found is that Index file "(blog).tumblr" no longer displays   "TotalCount": xxxxx, but rather   "TotalCount": 0, for each new blog added to the Index even though the total count was shown in the "Number of Downloads" column in the main queue window after the original crawl. Since "TotalCount":  is 0 when the Index is saved, restarting TumblThree at a later time results in the "Number of Downloads" column not having the original crawled number any longer. When the blog is then queued, it shows its being crawled again but then just quits without any files being downloaded. For each blog without the "Number of Downloads" column showing the "TotalCount": I must delete and re-enter that blog in order to download the images/videos.
