### ISSUE TITLE
!!!!

### ISSUE THREAD

**Issue by vipzkj** [johanneszab/TumblThree#219]
Backup my favorite list, tumblr.com/liked/by/xxxx this URL can only display 50, so it can not complete backup, what is the cause of this problem? Tumblr itself set? So how should we solve it?

**Comment by jpmc** [comment]
You may want to edit the title of this issue to something like "Download 'Liked By' list limited to 50 results" instead. Sorry if I don't have any further information though, I'm not sure if the 50 is a Tumblr-side limit or not.

**Comment by johanneszab** [comment]
> Backup my favorite list, tumblr.com/liked/by/xxxx this URL can only display 50, so it can not complete backup, what is the cause of this problem?

That's not true. You can see me downloading 147 likes in the screenshot of the README.md. I've downloaded more than 100.000 likes without issues.

Did you read the readme/website of TumblThree and followed the instructions given there? Especially the _application usage_ section, _downloading likes_, _third section_ mentioning NSFW downloads:

> iii. For downloading your own likes, make sure you've (temporarily) enabled the following options in your blogs settings (i.e. https://www.tumblr.com/settings/blog/yourblogname): 
>  ◾Likes -> Share posts you like (to enable the publicly visible liked/by page)
>  ◾Visibility -> blog is explicit (to see/download NSFW likes)

I'm rather certain it downloads all tumblr hosted photos and videos after modifying the code several times with the help of several users here (#171).

Otherwise, post (or send me by email) the public liked/by url, state your tumblr likes settings (as seen above under iii.), and your total number of liked photos and videos if you still think this is an issue.

**Comment by vipzkj** [comment]
[http://i4.bvimg.com/639961/b917bde9fac26864.jpg](url)[http://i4.bvimg.com/639961/91732b2b9e4bb78d.jpg](url)[http://i4.bvimg.com/639961/bf67a20ff150856f.jpg](url)[http://i4.bvimg.com/639961/bd6ddf31c5d16d9c.jpg](url)
Please see the picture, setting up should be correct, but the problem may not be produced because TumblThree is more like "like" public sharing can only show 50, setting the page mode after the third pages of the content. What is the problem?

**Comment by vipzkj** [comment]
This picture can be directly clicked outside the chain, and it can't be seen if it can't be opened. The connection can be seen in the browser.

**Comment by vipzkj** [comment]
[http://i4.bvimg.com/639961/5f04f3b924439245.png](url)

You can see that there are a total of 353, but fourth pages of Tumblr show no posts.

**Comment by johanneszab** [comment]
In the second screenshot (http://i4.bvimg.com/639961/bf67a20ff150856f.jpg), _enable_ the last checkbox: _blog is explicit_.
