### ISSUE TITLE
ToS and GDPR Changes -- Hidden Tumblr Blogs and Tumblr Search Not Working

### ISSUE THREAD

**Issue by jas0320** [johanneszab/TumblThree#229]
Issue started today but unable to download hidden Tumblr blogs.
TumblThree v1.0.8.48
Windows 10 Pro v1803
Cleared cache/cookies, re-authenticated
Receive the error message "You need to login to tumblr.com for downloading". Occurs with a new install of TumblThree as well. Happening on all hidden blogs. Interestingly enough the error comes up twice for each failed blog download.
Not getting a failed download error but tag Search does not appear to be working as well.

**Comment by johanneszab** [comment]
Looks like they've changed something again. It's a completely different thing that returns using the tumblr svc service.

Maybe it's because of the GDPR. I'm not sure if I have any time right now to investigate this, so maybe downloading hidden blogs is broken for some time if no one else cares to fix this.

Thanks for the head ups!

**Comment by johanneszab** [comment]
For what it's worth, looks like the [auth key extraction](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs#L220) for the svc service is broken as is returns 403.

**Comment by johanneszab** [comment]
Looks like they've changed the mechanism for the _SVC_ host (a service used to display the dash board blogs on the web page == hidden blogs) access authentication. 

Instead of querying a different host (https://www.tumblr.com/blog_auth/) and extract a key that is used in the following post requests to validate the cookie, it's now the same mechanism that is also used in the [tumblr search](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrSearchCrawler.cs#L114). It's easier. You only have to extract a key from the main page ([https://www.tumblr.com/dashboard/blog/_blogname_](https://www.tumblr.com/dashboard/blog/blogname)) that is subsequently added to the headers in each following request. The key depends on the cookie and thus on your login (username).

I've fixed that already in the code and the hidden blog downloads works again.

**Comment by johanneszab** [comment]
However even unregistered users now also have to agree to a new privacy statement ([https://www.tumblr.com/privacy/consent?redirect=https:%2F%2F_blogname_.tumblr.com%2F](https://www.tumblr.com/privacy/consent?redirect=https:%2F%2Fblogname.tumblr.com%2F)), probably thanks to GDPR, that breaks my hidden blog detection. So I'll have to fix that before uploading a new release.

**Comment by johanneszab** [comment]
Thanks. I think I've fixed this with the last two commits.

The search didn't work because for the search no cookies were loaded and thus you were always redirected to the new privacy statement. 
I've changed TumblThree now that it agrees to it automatically with [this commit](https://github.com/johanneszab/TumblThree/commit/3563d6cebf1a467151d6b8d6eee9806ddd6e6364). It's still not perfect however because for some reason you cannot load [cookies without subdomains](https://github.com/dotnet/corefx/issues/11795) and the agreement cookie is for https://.tumblr.com. Somehow I cannot retrieve it using the WinINet.dll, but maybe I'm just doing something wrong.
The workaround right now is to always agree it once at each application start, thus we're sending two requests at each startup to tumblr.com. It's not that much of a big issue, but still not 100% perfect though.
