### ISSUE TITLE
Where are blogs saved to?

### ISSUE THREAD

**Issue by fruvous** [johanneszab/TumblThree#233]
I'm having an issue where a tumblr blog is added but not showing in the list.  A folder is created at the save  folder with the rest of my saved blogs but it never appears on the listing.

I'd like to check the config file to see if there is something there that is screwing things up (duplicate maybe?) but I can't find the location where these are saved.  I have portable mode turned on.

Thanks.

**Comment by johanneszab** [comment]
The serialized classes in in the `Index` folder of `download location` are read into memory at startup. There is no config file that stores the added blogs. That would be `.\Blogs\Index\` relative to the TumblThree.exe file if you didn't change the defaults.

I've also written that in the README so that I don't have to answer the same usage questions over and over again.
