### ISSUE TITLE
New Tumblr ToS changes for GDPR (?) break hidden tumblr downloads

### ISSUE THREAD

**Issue by stuwm** [johanneszab/TumblThree#236]
The download of hidden tumblrs now seem to encounter the same issue as the normal ones (was #234). Could you please verify?

**Comment by johanneszab** [comment]
Still works for me. I've tested 4 different hidden Tumblr blogs with the latest release (1.0.8.50).

What is the exact error message? Does it happen for more than one hidden tumblr blog? Could you post the url? Does it completely stop crawling after the error message, or continue with some posts skipped?

Actually, the hidden Tumblr downloads were the first that broke due to the ToS changes (#229), a day later the api v1 was blocked that we use for normal blog downloads (#234). Right now the cookie is used in all the tumblr crawlers I've implemented (normal tumblr blogs, the search, the tag search, hidden tumblr blogs, password protected blogs).

As I've mentioned in #234, some hidden Tumblr blogs simply cannot be parsed correctly with the tools we are using, that's why I've added that message initially (see #217). But that should only skip some random posts. I've actually never encountered it myself.

**Comment by WyattLW** [comment]
Had the same problem, but as the hidden tumblr at first was downloading and i had problems like.. 10 minutes after.. i tryed more to find a solution.
Completely erase everything related to Internet Explorer cache / cookies, and run ccleaner..
rebooting always helps

CCleaner in particular worker for me..

**Comment by johanneszab** [comment]
> the hidden tumblr at first was downloading and i had problems like.. 10 minutes after

Then it's the issue that I've described in #234 that some posts simply cannot be parsed because they contain json like structures within the post. Using json.NET would probably help because it can be setup to simply ignore it, but I couldn't figured out yet how to do that with the Microsoft DataContractJsonSerializer api that TumblThree currently uses.

**Comment by WyattLW** [comment]
Can't help with that, never used..
But anyway a nice cleanse over cache and it worked, so nothing to bother about..
or there are more bugs related to it?

**Comment by johanneszab** [comment]
I'll close this as I see no problem with the tumblr hidden blog downloads, except for those posts that cannot be parsed. For this however, there already exists the mentioned issue.
