### ISSUE TITLE
I cannot recrawl entire queue of recently crawled tumblr search pages and tag search pages (2000+), in process I'm stuck.

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#252]
Hello.
I have a 2000+ search and tag search pages (tumblr.com/search/* and tumblr.com/tagged/*) that I recrawled from time to time. I have a problem. After full crawling in a couple of days, I reload the entire list into the queue and start crawling and find out that in the process I'm stuck in the queue on one of any pages on the indicator "calculate unique downloads" or just without any indicatior, only blue page name. I guess that it's possible that these pages are recrawled and changed too quickly, because some (probably many) pages do not have new files to download and during this time while these pages are changing, something violates the Tumblr limitations. If I come after a full recrawling in a week or two, then everything goes ok, the whole queue passes without errors. And if I starting recrawl them in a couple of days or immediately after a complete crawl of all the pages, then an error occurs. 
I sent a zipped Index folder to mail, which consisted only of tumblrsearch files, I did not send tumblrtagsearch files. their overall size is too huge, but I can send it too if it's needed for testing. These pages I recrawled yesterday and the day before yesterday, so I hope that not too many files should be downloaded. Thanks!

**Comment by johanneszab** [comment]
I'll not test 2000+ blogs.

Test if the attached release works for you, otherwise you'll have to submit a patch and fix this. I'm guessing the cause if the same as for you other requests. Either it's because you really have a bad internet connection, or you really reached some limits. Maybe you can lower your concurrent connection count?

I've not added the timeout extension to all webrequests as I though that no one fail some of them (like the first request for checking if a blog is actually online). I've added the code to all requests in the attached release. I've exhaustively written about the background in #116 and #214.

[TumblThree-v1.0.8.56-beta1.zip](https://github.com/johanneszab/TumblThree/files/2177657/TumblThree-v1.0.8.56-beta1.zip)

**Comment by Taranchuk** [comment]
I tested it, it seems the problem is gone, I'm now on 600+ blogs already downloaded, whereas I had problem on the 200+ blog approximally, I'll see if the problem goes on or not. I remember I had the same problem at recrawling thousands of image metadata, tomorrow I'll try recrawling them and write about the results.
Thanks for the help! I really appreciate it.

**Comment by johanneszab** [comment]
Can you check the latest release? I've included the crawling of the tumblr tag searches and tumblr searches in the rate limiter and I've also found a webrequest that was still missing the timeout extension, thus might have never timed out.

The drawback now however is, that if a request is timed out during the online check at the beginning, the blog(search) will be set as offline.

**Comment by Taranchuk** [comment]
Thanks, this solved the problem. :) twice downloaded a queue of thousands of blogs and everything downloaded without stopping! tomorrow I'll try again on image metadatas.

**Comment by Taranchuk** [comment]
Okay, this update had a positive effect on the downloading of the image metadata too. Just finished a recrawling of 4000+ image metadata and everything went smoothly. So this problem has definitely been fixed, so I close this topic. Thanks again! :) :+1:
