### ISSUE TITLE
Tumbler Hidden crawls missing multiple images

### ISSUE THREAD

**Issue by jas0320** [johanneszab/TumblThree#274]
Not all images are downloading when crawling a hidden blog. The issue seems to only occur if the image appears clickable (cursor changes and you click and a sub window pops up) but there is no actual pop up window. The blog example below is a mix of NSFW and just cool pics so apologize in advance. This blog has multiple examples - https://justalittlegin.tumblr.com/
This is one of the recently posted pics that does not download
https://78.media.tumblr.com/a962067c00c4f1c1b73a953551990444/tumblr_pfiwi0h8Wz1tcssjy_540.jpg
This seems like it may have started about the same time the raw image issue surfaced.
On the same blog, if the image is actually clickable it does download.

**Comment by johanneszab** [comment]
Thanks. Should be better now. It will now grab the text from the content of the "trail" of each post, instead of some fields of the post itself. The problem here is that the fields vary depending on the post type. Say you have regular (text) post, then the text seems to be inside a body field. If you have a picture post, then the text is in the caption field, and it seems to be different and even inconsistent for each/some posts. And then you end up having to concatenate and null check several different fields

The I'll close this. You can reopen it if you have any other posts that don't work. Then we can still concatenate all related fields and try it that way.

Thanks for the detailed description and providing examples!
