### ISSUE TITLE
Inline images aren't always being saved

### ISSUE THREAD

**Issue by sawbladex** [johanneszab/TumblThree#276]
Looking through the answers file from a sample tumblr of sketchydoodles.tumblr.com, I noticed that not all inline images get saved by tumblThree.

I think this is because they use the figure markup.
`
"</p><p><img src="https://66.media.tumblr.com/tumblr_mdr984EP3d1qh94bz.jpg"/></p>"`

Gets successfully saved while
`</p><figure class="tmblr-full" data-orig-height="449" data-orig-width="700"><img src="https://66.media.tumblr.com/8da5a200ab0510ff44e117077254b754/tumblr_inline_p41wgr49UJ1qh94bz_540.jpg" data-orig-height="449" data-orig-width="700"/></figure>`

Given they are both 66,media.tumblr.com links, that is the only difference that makes them different.

**Comment by johanneszab** [comment]
Works for me. The file is under a different name however if you use the default settings. That's because TumblThree tries to download a _raw file, and falls back to the next higher resolution (i.e. _1280). Thus, the picture in your post is under tumblr_inline_p41wgr49UJ1qh94bz_1280.jpg

![tumblr_inline_p41wgr49uj1qh94bz_1280](https://user-images.githubusercontent.com/1684561/46966314-a884df80-d0ad-11e8-85a7-d97edcc3a8fa.jpg)

**Comment by sawbladex** [comment]
Ah, so when doing these types of checks I should omit the file size data part of the filename.

Gotcha. well, you def solved my issue :)
