### ISSUE TITLE
Skipping mp4 videos

### ISSUE THREAD

**Issue by Patrick7070** [johanneszab/TumblThree#285]
Tumblr3 is skipping some videos and instead just downloading a jpg of the first frame of the video.
Ie if there is a video with a filename like tumblr_phwftlgJ561wkucd7.mp4
It will download the first frame of the video calling it: tumblr_phwftlgJ561wkubd7_frame1.jpg

**Comment by johanneszab** [comment]
No example, no fix.

Sound pretty much like [this](https://www.jzab.de/comment/4135#comment-4135) (which was fixed with [this](https://github.com/johanneszab/TumblThree/issues/270)), but since you didn't provide an example, there is nothing I can do.

**Comment by Patrick7070** [comment]
Don't really feel comfortable posting the site(s) it is having problems with.  But I did look into the links to see which videos it had no trouble downloading and they looked like:
https://vtt.tumblr.com/tumblr_p7rtpehPYN1ddvhq0.mp4 (which I believe was fixed in #270)

But it won't download videos with links like:
https://ve.media.tumblr.com/tumblr_phyuqn2O431ckubd7.mp4

**Comment by johanneszab** [comment]
Thanks. Will be fixed with the next release.

**Comment by johanneszab** [comment]
@euloghtos:

This is the issue you mean? I'll upload it tomorrow. Since I have changed quite a bit, I'll see how I'll be doing it. It might break other things since it's not really tested, thus I'm not sure if I should simply "release" it. Maybe I'll attach a beta release or something like this in an/this issue.

**Comment by euloghtos** [comment]
yeah, sorry should have replied here! a beta release would be great

**Comment by Patrick7070** [comment]
I think people are wanting to grab as much NSFW material before it gets pulled.  A beta would be great.
Right now I just create a list of URL in a text editor to grab the videos that are getting missed.

**Comment by johanneszab** [comment]
@euloghtos 
I'll release the next version maybe today, latest on Friday. I'll add a general regular expression search, that crawls for all "*mp4/*mkv" (i.e. video files) and all image files in everything the crawler sees. Maybe we'll able get some more external videos/photos, and for sure all unknown tumblr video hosts.

I only need to add missing check boxes to make this optional to the user interface as it will for sure add plenty of things more than once into the queue.

**Comment by Patrick7070** [comment]
Okay still having problems with version 64.

Here is a blog (NSFW  - Gay adult male):  (the page is small less than 100 files)
https://hairytroublebears.tumblr.com
(It is a hidden blog - and I am logged in)

Even with search for image/video patterns it won't download this video for example:
https://ve.media.tumblr.com/tumblr_phhepfvSQB1vmvcfu.mp4

It will download a file called: tumblr_phhepfvSQB1vmvcfu_frame1.jpg

**Comment by johanneszab** [comment]
![ve media tumblr](https://user-images.githubusercontent.com/1684561/49682513-c53e0200-fab5-11e8-8c90-06967992b50a.png)

Seems to work for me. I might take another look over the weekend though.

as for the image/video patterns _tumblr urls are excluded. Thats actually not was my intention was in the beginning (to exclude anything), but since not even the file names are consistent at tumblr, I wasn't sure how to implement a duplication check before adding a new download to the download queue and really cover everything, ..

**Comment by johanneszab** [comment]
Thanks for posting an example blog! It was actually quite a hassle to find a blog using the ve.media.tumblr.com host in the first place.

**Comment by Patrick7070** [comment]
Don't know what I was doing but everything is fine.  Thanks for your hard work on this.  Closing thread
