### ISSUE TITLE
Two different kind of blogs with the same name cannot be crawled in parallel

### ISSUE THREAD

**Issue by breakfastdragon** [johanneszab/TumblThree#286]
Hi everyone,

Thank you very much for a great program.  I'm currently having a problem with downloading my liked posts.  I've followed the steps - I've logged in through Connections and have changed the privacy settings, and have added the blog to the list - but when I try to queue it, it appears for a moment in the queue and then disappears.  I have tried http://www.tumblr.com/liked/by/wallpaperfx/ and that works fine, queues as normal.

I am trying to crawl my main blog at the same time, and I'm wondering if this is a problem with having the same name for items in the queue?  

I haven't seen anyone else with this problem, so please let me know if there's a simple fix that I'm missing.

Cheers!

Breakfast.

EDIT: Can confirm that it seems to be a problem with having the same name.

**Comment by johanneszab** [comment]
Thanks for open this issue.

I'll have this fixed with the next release. It's not a technical issue, [the code](https://github.com/johanneszab/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Controllers/CrawlerController.cs#L178) that should prevent TumblThree from crawling the same blog twice just needs to be updated since it's now capable of crawling different kind of websites/tumblrs.
