### ISSUE TITLE
I can't seem to download mine or anyones likes on tumblr.

### ISSUE THREAD

**Issue by himitchy** [johanneszab/TumblThree#293]
i've authenticated in the programme, set my privacy to explicit and liked posts to visible, put the link to my liked posts in and clicked crawl. it adds to the queue but it won't download anything. i tried other peoples likes and they do the same thing, just adds to the queue and won't actually begin downloading.

https://www.tumblr.com/liked/by/darkest-thxughts that's the link i used to download my likes.
it is vey NSFW so pre warning haha.

**Comment by johanneszab** [comment]
Your provided url is working for me. I'll be brief, since I don't have time to answer everyones question right now.

Make sure you've:
* Added your "blog" (the likes blog) from the blog manager (left side pane) to the queue (right side, shared with the details pane) by clicking on "Add to Queue" or by dragging and dropping or double clicking on it.
* Turned on the actual crawler by clicking on "Crawl". It will start with the first item in the queue.
* If it's working, there should be a blue/greenish bar next to the item in the queue.
* Make sure you didn't mess up the settings. Click on your blog in the manager, open the details window, and make sure something (i.e. download photos) is actually selected. Also note the format of the date (YYYYMMDD), in case of you specified a "download from/to".
* The queue should regularly update about the progress, and the download counter in the manager should increase.

If that doesn't help you, try browsing in the closed issues here or on [my website in the comments sections](https://www.jzab.de/content/tumblthree).

**Comment by DStrifer** [comment]
how to download liked pics? why i can`t login in setting? wtf is this - TFA detected enter auth cod ?

**Comment by stillwaterspony** [comment]
try using this release, it let you login manually and solved the TFA issue: https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.51

**Comment by himitchy** [comment]
im not sure what changed but it just started working, i didn't change anything but it works perfectly now. thanks so much for your hard work!
