### ISSUE TITLE
Download my Tumblr Archive for $5 via Venmo

### ISSUE THREAD

**Issue by Jobinn** [johanneszab/TumblThree#305]
Hello Ya'll.

 As everyone may know, Tumblr is shutting down all "adult content" soon. I have amassed a large number of photos and videos over the years and would like to copy it to another blog. Since i'm, technically challenged and dont have a windows computer to support TumblThree - I'm offering an easy $5 to anyone who can copy my blog including photos, videos, or any other reblogs. A zip file sent to an email would be great. Let me know if you're up for the "challenge"!

http://teardroptitties.tumblr.com/

Best,
Jobinn

**Comment by Hrxn** [comment]
There are other alternatives. Even on GitHub.

Just as an example:
https://github.com/bbolli/tumblr-utils
https://github.com/RipMeApp/ripme
https://github.com/mikf/gallery-dl

**Comment by omque** [comment]
Done. Link [here ](https://we.tl/t-WYjYZ1xYaJ)- it will expire soon.

You can kick $5 to the developer of [TumblThree (PayPal) ](https://www.paypal.com/donate/?token=OuEmKs9DmfZgQFgyMs9pYn_r9MAPdCLN6IwKb7WUB9GUvowugfJekALRcm1tKjIwi2zdC0&country.x=US&locale.x=US)or Tumblr-Utils (which I actually used for this since it preserves text/comments) instead of sending anything to me. 

If you have questions/etc DM me on Twitter (username is the same), and go ahead and close this issue.

Cheers!
