### ISSUE TITLE
Only downloads text files, no media

### ISSUE THREAD

**Issue by DudeBroChill** [johanneszab/TumblThree#310]
The app appears to be downloading and it even shows how many files have been downloaded for each blog... however when I go into the folder that was created for each blog the only files in each is the following: answers.txt, images.txt, images_url.txt, links.txt, texts.txt, videos.txt, and videos_url.txt. There are no actual images or videos stored anywhere. What am I missing?

**Comment by dgellom** [comment]
Me too.
Only received a list of URLs in separate txt files and metadata for every post in JSON

![1](https://user-images.githubusercontent.com/28863406/49541720-5194cd00-f8dc-11e8-8c6c-f2da95c5dbd6.png)

**Comment by johanneszab** [comment]
You've enabled the _download url list_ option in the _Details_ of that blog.

In that case, TumblThree will not download any binary files, but __instead__ put all the urls of these files into the **_url.txt files. Read the README.md (main page) here, the _tool tip_ of that particular option or the change log:

It says:
~~~
Download a url list of the binary files instead of the actual files.
~~~
Someone requested this months ago, I've implemented it. I don't know why this would be useful, but it's there.
