### ISSUE TITLE
Both # of Downloads and Downloaded Files are blank no matter what Liked/By or Blog I add, please help

### ISSUE THREAD

**Issue by DraggoonLord** [johanneszab/TumblThree#315]
![capturetumbl](https://user-images.githubusercontent.com/45684502/49638134-e70f8a00-f9cc-11e8-9b14-fb4734142ac2.PNG)
As you can see in the photo, even if I add a blog to the queue or crawl through it, it does not detect any posts nor does it download anything, I've reinstalled several times and cleared all the settings as it only became an issue after I added a single Liked/By blog. Hopefully this can be resolved

**Comment by johanneszab** [comment]
Does the queue show any progress, something like: "crawling page x of x" or "evaluated x of x posts" ? If not, try to delete your settings in %LOCALAPPDATA%\TumblThree while TumblThree is closed.

If it shortly shows some progress, but then terminates without downloading anything, make sure you have something meaningful selected in the _Details_ pane of the blog you are crawling. Is there anything to download selected at all, download of reblogged post, a valid date format? Otherwise it might simply not download anything, because your conditions do not yield anything to download at all.

**Comment by DraggoonLord** [comment]
The image posted is what it looks like after leaving it for approximately an hour to see if it’ll load on it’s own. I’ve not seen a evaluation or # of pages it’s crawled, and I made sure to delete the settings in App Data when re-installing. As for there not being anything to download, the blog i have selected currently has over 25k liked posts, so it should have an abundance of things to crawl through. I’ve also made sure to set the download to start a minute or so after I close out of settings, only for nothing to occur. The issue could possibly be that my set conditions don’t yield anything but I’m not sure what setting I’d have to change for the conditions to work. I have attached all 4 of my settings pages so that you can see what I have selected and possibly find where I might have made the wires cross accidentally. As for the blog itself, it has likes visible, explicit content box checked, and everything listed that's required to be able to download its likes.

![settings 1](https://user-images.githubusercontent.com/45684502/49641798-d532e480-f9d6-11e8-9928-dfbd8f9f41b8.PNG)
![settings 2](https://user-images.githubusercontent.com/45684502/49641800-d532e480-f9d6-11e8-8f57-e01e44949ca6.PNG)
![settings 3](https://user-images.githubusercontent.com/45684502/49641801-d532e480-f9d6-11e8-9359-a99bb7bb18b4.PNG)
![settings 4](https://user-images.githubusercontent.com/45684502/49641802-d532e480-f9d6-11e8-9b0d-80b139e54826.PNG)

**Comment by Anonymous-Mischief** [comment]
Alright so this may be the reason you're having problems viewing the blog. There is a particular visibility setting in tumblr that only allows for you to view the blog from your dashboard. If you own this account then log into your account. Go to https://www.tumblr.com/settings/blog/draaggoonberry, scroll towards the very bottom until you reach the Visibility section and turn off the first visibility option. May also try turning off the second option as well in that section. Then try crawling your blogged for liked posts.

**Comment by DraggoonLord** [comment]
I have the first visibility option turned off as shown, however I am unable to edit the second and the third, so I don't know if turning those off would fix the issue. Regardless, as my settings are now, it is still unable to detect anything to download.

![visibility](https://user-images.githubusercontent.com/45684502/49675297-afd7c200-fa3a-11e8-961b-7c3f1bce3241.PNG)

**Comment by johanneszab** [comment]
Did you do what I told you to do?

1. Delete all your TumblThree settings in %LOCALAPPDATA%\TumblThree while TumblThree is closed
2. DO not modify any settings except for logging in in TumblThree
3. Add your blog as before, add it to the queue, click 'Crawl'.

**Comment by johanneszab** [comment]
![draggoonberry1](https://user-images.githubusercontent.com/1684561/49678360-1e8d3d80-fa84-11e8-813b-31334411c233.png)

**Comment by Anonymous-Mischief** [comment]
Interesting. My thinking is that if you can't find a blog from a search or through a link with the format http://<blog_name>.tumblr.com, then TumbThree wouldn't be able to access it. So if somehow you're able to get that second option turned off as well, and you're able to pull up the blog through a search, then I think TumblThree should be able to crawl it. Otherwise if it's not searchable, then TumblThree can't crawl it. Just my thoughts anyway. Sorry mate,

**Comment by johanneszab** [comment]
The second (and third) visibility options are irrelevant for TumblThree to pick it up. The first one allows access via the www.tumblr.com/liked/by/ -url which is enough. The third allows access to explicit flagged content however.

I've also written this in the [README.md](https://github.com/johanneszab/TumblThree), ...

**Comment by DraggoonLord** [comment]
I just did all the steps you listed, however, still nothing. Apologies for not including the details in my previous post. This is what it looks like after I have reset everything, logged in again, readded the blog to the queue, and hit crawl.

![details](https://user-images.githubusercontent.com/45684502/49681749-8afc4280-fa6c-11e8-9ef3-a207c27daa09.PNG)

**Comment by johanneszab** [comment]
hmm.. looks quite right. Weird however as the same settings seem to work on my end. 

May I ask where you extracted the .zip to? Do use a proxy, vpn? Can you download anything else, like a regular blog? For example this one? https://wallpaperfx.tumblr.com/

**Comment by DraggoonLord** [comment]
I simply moved the zip file from my downloads to a folder on my desktop, and extracted the folder with the .exe to the same folder where the zip is. I don't use any proxies or vpn's and am just downloading off of a normal internet connection. I also am able to download the blog you linked perfectly fine. I decided to try and download that same blogs liked/by page. Which worked, so I tried the original blog I tried on, and now it is downloading files but the number of downloads is still blank. I have no idea why it started to work all of a sudden as i didnt change anything in settings or details, my only concern is will this result in an error such as an incomplete download or should I just leave it be?

![wallpaper](https://user-images.githubusercontent.com/45684502/49682629-0cf46780-fa7d-11e8-805e-af115eed1ac3.PNG)
![liked by](https://user-images.githubusercontent.com/45684502/49682688-55f8eb80-fa7e-11e8-8388-87ef81aa1441.PNG)

**Comment by johanneszab** [comment]
> Which worked, so I tried the original blog I tried on, and now it is downloading files but the number of downloads is still blank. I have no idea why it started to work all of a sudden as i didnt change anything in settings or details, my only concern is will this result in an error such as an incomplete download or should I just leave it be?

You can leave it running. When the "number of downloads" will be set depends on the blog you are crawling. For regular tumblr blogs, that number is known before. For likes I've not implemented this (but right now I wonder why because the number of likes value is at the top of the page, .. simple enough) and it will be set after you stop the crawl, or the crawler is done crawling.

**Comment by Hiina8059** [comment]
> Does the queue show any progress, something like: "crawling page x of x" or "evaluated x of x posts" ? If not, try to delete your settings in %LOCALAPPDATA%\TumblThree while TumblThree is closed.
> 
> If it shortly shows some progress, but then terminates without downloading anything, make sure you have something meaningful selected in the _Details_ pane of the blog you are crawling. Is there anything to download selected at all, download of reblogged post, a valid date format? Otherwise it might simply not download anything, because your conditions do not yield anything to download at all.

If you happen to have some time to answer one more question then I'd like to ask something about ''evaluated x of x posts''.

Nothing worked for me so I read the thread and deleted the TumblThree settings in Local App Data while closed, and didn't change any settings when I started it up again. Still nothing worked. So I changed the download destination to a new folder and made sure my browser information was correct. Still nothing. Then I logged in again and enqueued the wallpaperfx likes. Somehow the entry went green and showed me ''Evaluated xxxx tumblr blog sites'' without actually showing how many posts were to be downloaded, and alas nothing shows up in the folder. I removed the wallpaperfx entry and tried it on my own liked by/string and the same thing happened. I have over 35.000 liked posts and right now it says ''Evaluated 3400 tumblr blog sites'', still with nothing actually showing up in the folder. Every time I stop it, it starts over from scratch, so I've been letting it accumulate numbers but I'm not sure what it's doing

I'm happy there is at least some sort of progress but it still doesn't download anything :( 
![prob1](https://user-images.githubusercontent.com/45703661/49700130-ff54f400-fbda-11e8-9ea2-c1aa186c6a29.png)

**Comment by johanneszab** [comment]
If you have the "Download images" and/or "Download videos" selected at this point, then it actually should download something. At least I am not doing anything different.

![veneziamore](https://user-images.githubusercontent.com/1684561/49700275-c453c000-fbdc-11e8-9962-e2519d14807a.png)

I've added the blog/likes, put it into the queue, pressed crawl and it immediately started downloading.

I can only guess at this point without starting TumblThree in Visual Studio at your machine in debug mode. Maybe it's an issue with your antivir? Maybe you can check if there is something going on there, otherwise I don't really know.
