### ISSUE TITLE
why? why Error 1?

### ISSUE THREAD

**Issue by DStrifer** [johanneszab/TumblThree#319]
I logged in.
I want to download my liked pic from tomblr
I use this https://www.tumblr.com/liked/by/MYBLOG
and nothing, ur program tells me that my blog is offline ERROR 1. That`s it. 
plz help.

**Comment by johanneszab** [comment]
You didn't do what is written in the [README.md](https://github.com/johanneszab/TumblThree/). Simple as that. You likes url is not publicly visible using the link you've posted. For example, since I do not have the actual url:

![non_existing_like_url](https://user-images.githubusercontent.com/1684561/49678696-77f66c00-fa86-11e8-9cd2-cae0ceafeecb.png)

I've also answered the same question here and on my website several times in the last days.

**Comment by DStrifer** [comment]
i`m sorry, my fault, i did not know about this restriction settings. thank u for ur answers, i will try later.

**Comment by sachk** [comment]
This issue should be closed.
