### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by LTGM** [johanneszab/TumblThree#334]
Del

**Comment by LTGM** [comment]
All was left by default, 8-4-1. Even If I switch 4-2-1 it won't help. Also I see a message 'confirming to the tumblr privacy consent failed. there might be a connection issue' even tho I passed verification and have this session as active if I check it on the site?

**Comment by LTGM** [comment]
It doesn't seems like its downloading, progress bar gets stuck and nothing moves...

**Comment by LTGM** [comment]
Tried new version still have the issue. Even with 1-1-1 settings still no luck.

**Comment by johanneszab** [comment]
> Also I see a message 'confirming to the tumblr privacy consent failed. there might be a connection issue'

I don't know. It all sounds kinda weird, and since I've never seen this personally, I cannot really help you. I'd need to to reproduce it locally, but it sounds like something with your setup/connection/locally . Are you behind a VPN/proxy or similar?

Maybe you can check your anti virus/firewall, see if it has any activtiy and tries to block TumblThree.

That only the images are 0 kb is also strange since the file downloader that loads the images and the videos is the exact same code. But on the other hand, if you say that the verification passed, and you could download some videos, that would indicate that TumblThree at least at one point could connect to Tumblr. Thus all the other connections should work in theroy as well.

**Comment by LTGM** [comment]
OK now what the hell really. If I click like 10 times in 5 minutes I can finally start it and colors appear with the progress bar, blog was downloaded with the latest version...I will continue to investigate, don't have much time left
Pretty sure it's not AV, I use 360 security and I disabled it completely few times to check if anything interrupts the grabber.
