### ISSUE TITLE
Can you add support File URL indexing?

### ISSUE THREAD

**Issue by gorzola** [johanneszab/TumblThree#349]
tumbler will change the status of specific posts to private from December 17th.
I am backing up files, but I can not finish it until December 17 because the amount of files is too large.
TumblThree extracts only URL addresses of image files and video files without actually downloading the files, records them in the txt files, and makes it possible to download later (even after December 17)
Can you do it?

**Comment by johanneszab** [comment]
> TumblThree extracts only URL addresses of image files and video files without actually downloading the files, records them in the txt files, and makes it possible to download later (even after December 17)

uhhm? You actually want to feature to be implemented into TumblThree, or you are wondering why this is happening?

You need to enable/disable the "download url list" option as shown exemplary in this screenshot. This will download urls of binary files (i.e. images, videos, audio) instead of theses files itself.

![tumblthree_addblog1](https://user-images.githubusercontent.com/1684561/49919273-57734b00-fea6-11e8-9d77-c42c21bfc0db.png)

**Comment by Hrxn** [comment]
?

If you want to download files later via direct URL, you need to *enable* the download url list option.

**Comment by gorzola** [comment]
> 
> 
> ?
> 
> If you want to download files later via direct URL, you need to _enable_ the download url list option.

Thanks. Hrxn
