### ISSUE TITLE
When Tumblr is empty

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#40]
I encounter a strange issue (and i cannot put my finger on it myself).
If i have a tumblr site where files were downloaded in the past (i don't try with a new one with the same properties). If the tumblr now have no post (by example davidcharlec.tumblr.com).
If i add this tumblr in the queue and launch TumblThree, the blog is put in processing state and it's like it enters in a no end loop as it never stop and release the process.

Maybe here:
`totalPosts = Int32.Parse(blogDoc.Element("tumblr").Element("posts").Attribute("total").Value);`

If totalPosts is 0 then we must exit this function? If i launch the program through the IDE i see the line just after raise an exception in this specific case:
`ulong highestId = UInt64.Parse(blogDoc.Element("tumblr").Element("posts").Element("post").Attribute("id").Value);`

> An exception of type 'System.NullReferenceException' occurred in TumblThree.Applications.dll but was not handled in user code
> 
> Additional information: Object reference not set to an instance of an object.

**Comment by johanneszab** [comment]
Well, actually, it's quite easy. You've already tackled it down. Just open your example blog in a browser [using the api](https://davidcharlec.tumblr.com/api/read/).

In the response from the server there is no Element("tumblr").Element("posts").**Element("post")** hence it cannot get parsed and you get the NullReferenceException. You can use the [null conditional operator](https://msdn.microsoft.com/en-us/library/dn986595(v=vs.140).aspx) in this case as it checks for null before accessing the member. 
But since we didn't set the highestId to zero before you would hit immediately an ArgumentNullException instead. So, if you combine the null conditional operator with the [TryParse](https://msdn.microsoft.com/en-us/library/f02979c7(v=vs.110).aspx) function which doesn't throw an exception if it cannot parse the value and sets it to zero instead, we are good to go.

We then just process the loop once, there is nothing to do inside, but that's totally fine in my point of view.

**Comment by amigre38** [comment]
Ok i will try to understand how you correct it in order to be able to do it myself in case i found another one like this ;)
