### ISSUE TITLE
Bugs in the version 1.0.4.35

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#51]
1) With the enabled mode of downloading the list of url they do not download at all, a text file with them is not created.
2) There used to be a bug when after adding hundreds of blogs to the program half of them at the start were shown as offline blogs, but after a while their status changed to online, in the next versions this bug was removed, at least this error is not reproduced on the version 1.0.4.24. And in version 1.0.4.35, this bug again appeared. And when the program changes the status of all offline blogs to online, then after the program is closed and reopened, their status is reset to offline status with a subsequent change to online.
3) Minor bug: when I enter into the program, I always see an error at the top "Could not restore UI setting".

If necessary, I can send a list of hundreds of blogs to the mail for testing.

**Comment by johanneszab** [comment]
1. You have to check above which kind of url you want. If you check _download images_ and _Download url list_ below there should be file in the blog folder names *images_url.txt* containing all image urls.
2. Its probably caused by the rate limiter and where/if I've added it should check for the blogs online state and postcount before adding it to the manager. These checks take time as they are limited thus might not end up filling the dispatcher too quickly.
3. Remove your Settings.xml in the AppData\Local\TumblThree folder. Maybe I've changed some localizations.

**Comment by Taranchuk** [comment]
Thanks, now I understood how to download the list of URLs. I think it was not obvious how could download the list of URLs. Maybe you should add a hint in the pop-up message? And I also found one bug: when I select a group of blogs and in summary details view I select the mode downloading images and the list of URLs, the program does not download url lists anywhere. Only through a single mode the program downloads a list of links.

**Comment by johanneszab** [comment]
I probably forgot to set up the multi selection.
I won't do anything for the next three weeks either since I won't be here, so If you find anything else, just put it in here. I'll fix it later then.

Thanks for reporting!
