### ISSUE TITLE
Bugs in version 1.0.4.36

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#54]
When i replace the latest one and launch it with my folders i get this error on top:
![image](https://cloud.githubusercontent.com/assets/26059690/24648079/b4516674-1922-11e7-82dc-574c69dff0ec.png)

**Comment by johanneszab** [comment]
If you just restart the application then, does it reappear?

**Comment by johanneszab** [comment]
I've also had this, but sometimes it's not there and the error should appear anytime if that's true what is stated there.

Since that wasn't the case for me, and also not for new blogs, it might have some other cause. I've moved around the fields of the database, .. but that's really far fetched and the error should not state this.

We can add the blogs on the UI thread though, then the state error shouldn't happen.

**Comment by amigre38** [comment]
I get this on another one each time i launch it. I mean the line displayed is never the same one. One blog or another.

**Comment by johanneszab** [comment]
Ok, then we'll have to run that on the UI thread. Wired though that it doesn't happen for me anytime. I've tried it with around 30 blogs or 5. Maybe some race condition ..

**Comment by amigre38** [comment]
Yes it could be i have more than a thousand blog in list (even if a lot of them have never been downloaded)

**Comment by johanneszab** [comment]
Does this fix it for you? : [TumblThree-v1.0.4.36.zip](https://github.com/johanneszab/TumblThree/files/892608/TumblThree-v1.0.4.36.zip)

**Comment by amigre38** [comment]
Yes it is! This version works fine, no more error message when loading the list.

**Comment by johanneszab** [comment]
Ok, thanks for testing! Then I'll upload this one.

**Comment by amigre38** [comment]
No problem! i do what i can to help ;)

**Comment by johanneszab** [comment]
Okay, I think I've refactored most things now. All methods only do one thing and changes shouldn't have such a big impact or break other things. I also hope the code is easier to understand now. Finding names isn't always the easiest task ;)

**Comment by keokitsune** [comment]
Switched to new release, was told that it could not read library so I manually re added all blogs, I have them all set to download video/pic but when they crawl nothing is downloaded, the crawl ends with 0/however amount.  And if I leave it running the whole program will stop responding a crash after about 3 minutes.  It seems to download new posts that have been made since that last crawl from the old version of the program but wont recrawl files that are already existing in the folder despite the option to scan data base is turned off. If I manually delete the blog file, things download like normal.

**Comment by johanneszab** [comment]
Thanks. i'll look into this once the code is more or less back in a running state ..

**Comment by amigre38** [comment]
I try deleting the files and retrying to download it and that work. So the problem is related to these files i attach here that look like they put the problem on freeze.

[01graphy-tumblr.zip](https://github.com/johanneszab/TumblThree/files/929752/01graphy-tumblr.zip)
[01graphy_files-tumblr.zip](https://github.com/johanneszab/TumblThree/files/929753/01graphy_files-tumblr.zip)

While doing these tests i found another problem. some handles are not closed. I delete this blog, add it again another time. Crawl and download it (i delete the content of the folder first). I see well the files in the target folder. I then (having the TumblThree program at screen) try to delete the newly downloaded content. But one of the file cannot be deleted. I then close TumblThree and the file handle was released (and i can delete the file) so maybe somewhere at least one handle is not closed properly.

**Comment by amigre38** [comment]
I can confirm that even with the latest version this problem is not corrected. Can i do something to help here?

**Comment by johanneszab** [comment]
You'll either have to convert all your old blogs again, or clean the data structure in the _files.tumblr files. Your problem is that it's stuck at 

In [those attached files](https://github.com/johanneszab/TumblThree/issues/54#issuecomment-294840598) the Name field is messed up. Looks like we've release a pre-version to early and the conversion didn't work at that time properly.

Anyways, in the attached files the Name property looks like this:
```"Name":	".\\Blogs\\Index\\01graphy_files.tumblr",```
but it must be:
```"Name":	"01graphy",```

You can probably use Notepad++ for this or any other more advanced editor of your choice to mass editor files in a directoy. I've linked a stackexchange question [here](https://github.com/johanneszab/TumblThree/issues/64#issuecomment-294370372).
