### ISSUE TITLE
Index files

### ISSUE THREAD

**Issue by amigre38** [johanneszab/TumblThree#56]
Hi, i don't know why but some files disappears in the index folder (may be my hard drive not the code) but that raise a problem.
If the _files.tumblr is deleted, there is an error in the label about it in the interface. So i try to put the blog in the queue to download it again (after all it's not a big problem) but the download never start. Maybe the _files.tumblr file is needed?

On another hand i have a _files.tumblr but not the tumblr file related. Could it be possible to have a way to recreate it automatically maybe? Or any idea how to handle this other case?

**Comment by amigre38** [comment]
I think it's related i get andrew-lucastudio_files.tumblr_files.tumblr files in this index folder.
I just readd a tumblr blog for which i have the andrew-lucastudio_files.tumblr existing but not the andrew-lucastudio.tumblr, and i download it again. And i end with this strange file with double suffix

**Comment by johanneszab** [comment]
I also just stepped over some weirdness with the file loading :/ and pushed some changes (@448d921).

I've put it now in the corresponding data models and let them handle the loading so that there are less ugly assignments all over the code which probably break things. I guess that's a better way to handle this.
I noticed that the _files* loading doesn't work if the index files were moved to a different place.

Not sure if that fixes your problem too though. Doesn't sound like it should help there.

**Comment by amigre38** [comment]
I have this error with the latest release, not sure i have previously or not.
![image](https://cloud.githubusercontent.com/assets/26059690/24728718/64e36404-1a5b-11e7-87d4-cc654e559425.png)
It's like the file was processed by another function and it tries to download it again. You have the blog name in the file path if needed.

**Comment by amigre38** [comment]
In fact i relaunch the project in VS (because i can't see the live debugging) and i try to download a blog with few files and that was already downloaded. And the error appears on this line:

bool finishedDownloading = downloader.Result;
in the function:
 public void Crawl(IProgress<DownloadProgress> progress, CancellationToken ct, PauseToken pt)

If it helps?

**Comment by johanneszab** [comment]
Those entries were there before too. We currently just put everything in a queue the crawler detects. Seems like if the are two posts with the same picture too close together we start them twice. Or the detection is wonky and add the same file twice.

Now, we can simply check of the url is already in the list of duplication calculation/stats before adding it again. I couldn't do that before because the downloader takes things out of the queue while we add things. So if the downloader starts a file, then we add it again, because it's not in the list. 

Or we check if the file exists already before downloading. Not sure whats better.
