### ISSUE TITLE
"Could not load library" on startup

### ISSUE THREAD

**Issue by speciose** [johanneszab/TumblThree#6]
I've had an issue with no free space on my hard drive and after that I've lost all my library.
When I start TumblThree, I don't see any of my previously added blogs. Sad. Maybe this could be fixed in the future. Definitely something with available space on hard drive. Seems like program don't know what to do when you don't have free space and do something wrong instead. Right now I have free space but it's too late.

**Comment by speciose** [comment]
Oh no. It happened again. Seems like I need to reinstall my TumblThree

**Comment by speciose** [comment]
Is there some records in the registry related to TubmlThree? Because I still get this error and can't do anything to reset

**Comment by johanneszab** [comment]
No, nothing in the registry, just settings files in *AppData\Local\TumblThree\Settings\* which you might try to delete.

Either the directory is wrongly saved or it cannot read one of your .tumblr files, would be my guess.
So maybe you reset your directory via the application itself or delete the settings files or you might have to try to figure out which .tumblr file might be broken. That would be easy to do with a debugger but quite cumbersome via try and error. 
Might make sense to rewrite [the section](https://github.com/johanneszab/TumblThree/blob/caecdb91462be397a6176c1af83bee19587c28cd/src/TumblThree/TumblThree.Applications/Controllers/ManagerController.cs#L118) so that the error states which file is broken or if the settings are corrupt.

**Comment by speciose** [comment]
I've deleted TumblThree and `AppData\Local\TumblThree` folder
Installed new 1.0.2 version and the issue has disappeared
Thanks! If there will be this error again I'll text here with more information about what Library File was causing the issue.

**Comment by speciose** [comment]
I got it!
So the problem was with some of *.tumblr files inside `Index` folder (which is inside Download destination folder). I've deleted two files that were corrupted and all my library reappeared! It's a miracle. Thanks again. It's just wasn't clear for me that there is this `Index` folder. Maybe your should name it "_index". I don't know.
