### ISSUE TITLE
Calculating & Removing Duplicates

### ISSUE THREAD

**Issue by sup3ruser** [johanneszab/TumblThree#71]
.42 (newest version) gets stuck during this process.  There is no error shown, app is still responsive.  It just sits there forever.

(Cause Im only crawling one blog at a time, and cause its stuck during this process, it never moves to the next blog and scrape.)

Jerome

**Comment by johanneszab** [comment]
Can you check the Links list in one of your _files.tumblr where it does not continue to processes. If there is anything except just a filename or a numeric id then that's the culprit. I do know for sure that in one release I've messed up the processing and other stuff also went into the database.

If there is nothing, send me or attach one of those blogs (the _files.tumblr and .tumblr). Otherwise I won't do anything since it works here as intended.

**Comment by johanneszab** [comment]
You might also want to check if the Name field is right, for more [check here](https://github.com/johanneszab/TumblThree/issues/54#issuecomment-298957769)
