### ISSUE TITLE
Not downloading pictures in answers

### ISSUE THREAD

**Issue by nar001** [johanneszab/TumblThree#73]
So I just realized that it's not dowloading pictures embedded in answers? Is it a bug, or expected?

**Comment by johanneszab** [comment]
It's simply not implemented. I actually don't use tumblr myself and i didn't know there is an answer post type. For the tumblr implementation I took the hard way and we're stepping down all the paths of each post kind instead of just use regular expression or some type of general matching.

It's probably just 3-10 lines of code and similar to the other post kinds already implemented though. You might want to add it for yourself, or wait till someone does it. I don't have time to do this right now though..
