### ISSUE TITLE
Still not downloading all likes.

### ISSUE THREAD

**Issue by xxxoverkill** [johanneszab/TumblThree#78]
Went from 300 ish to 3000. But wont go further. Whatever you did worked however. Still needs some tweaking though.

**Comment by johanneszab** [comment]
Follow-up to #77.

**Comment by CrazyKoala** [comment]
Unfortunately , this still happens. Got more than 3600 likes, but only 500 gets downloaded :(

**Comment by johanneszab** [comment]
Like I've said before, no url, no help. I'm really tired of repeating this over and over again in every issue.

**Comment by johannesvogel** [comment]
@johanneszab 

I guess the problem here is, that the user wants to download his own likes. Therefore he knows, that there are 3000+ likes. But the `https://www.tumblr.com/liked/by/user/` page actually does not show all of the likes (for example I think likes of posts in hidden/18+ blogs are nor shown) as this page is a "public page". This could be solved by allowing to crawl the private page `https://www.tumblr.com/likes/` which includes all liked posts.

**Comment by johanneszab** [comment]
> Therefore he knows, that there are 3000+ likes. But the https://www.tumblr.com/liked/by/user/ page actually does not show all of the likes (for example I think likes of posts in hidden/18+ blogs are nor shown) as this page is a "public page". 

I was sure that I've already seen some "public" (i.e. https://www.tumblr.com/liked/by/user/) liked/by-blogs with NSFW content, so I just searched for some, and these here surely contain 18+ content:
https://www.tumblr.com/liked/by/swissescort
https://www.tumblr.com/liked/by/panties69/page/2/1507013037

Thus, I just added some NSFW content played around with my settings, and you'll have to enable these two options under your blogs settings (https://www.tumblr.com/settings/blog/blogname) to fully download your photo/video likes with TumblThree:
* Settings-> blog -> Likes (to enable the public liked/by page)
* Settings -> blog -> Visibility -> blog is explicit. (to see NSFW content)

Thus, if you don't change the visibility option, the public liked/by page will not show NSFW content. I'll update the instructions for downloading likes on my website and in the README.md to reflect this. 

Thanks for the tip!
