### ISSUE TITLE
Authentication for Tumblr with Yahoo openid does not work 

### ISSUE THREAD

**Issue by googlysmooth** [johanneszab/TumblThree#83]
When a Tumblr user, who signed up to tumblr with Yahoo (using openid),tries to authenticate in Tublthree settings,  the dialog for the Yahoo openid authentication shows, but always gives a invalid password. 

![image](https://cloud.githubusercontent.com/assets/20747888/26408004/a3fdc604-406a-11e7-9902-40cbf63fa49e.png)

Yahoo login works fine all by itself. 
![image](https://cloud.githubusercontent.com/assets/20747888/26408150/0925f056-406b-11e7-9262-495e3f720caa.png)

**Comment by johanneszab** [comment]
It does work. My account is also yahoo coupled (OpenID), login works without problems. Sorry, no issue there. I'm quite sure since the whole browser is the actual Internet Explorer. Invalid password does not seem like I have to fix anything here.

Try the Internet Explorer directly, see if that works. Just login and and close it. TumblThree will use the same cookies.

**Comment by johanneszab** [comment]
Can someone else verify this bug? As I've said, it works here fine with my account.

**Comment by googlysmooth** [comment]
No, its ok now... Sorry, must have been a keyboard glitch or so, you can close.
