### ISSUE TITLE
Tumblr.com not accessible using VPN.

### ISSUE THREAD

**Issue by zzf859313645** [johanneszab/TumblThree#91]
add blogs then 'Add to Queue' can't click,if i want "double click on a blog adds it to the queue",it just crash。I also tried to pull the project to the queue, but it only keep a few seconds then disappeared。i try this app on win10 and win7,use the different versions, all cant work. besides,i also use vpn. Do I need to do other operation,hope to get some help .and thank you for the program.and the Screenshots
![default](https://user-images.githubusercontent.com/29424124/27121654-c64c304a-511a-11e7-9ce4-966817957b08.jpg)

**Comment by johanneszab** [comment]
Blog is shown as offline, that's why it's not crawlable. Check your connection settings, or describe here in detail how you connect to your VPN, what kind of VPN it is, your windows version and what VPN client you use.

Finally, can you access tumblr.com without the VPN, can you access it with your VPN?

**Comment by johanneszab** [comment]
Could you also try [this version](https://github.com/johanneszab/TumblThree/issues/33) of TumblThree? Remove your blog and re-add it. It could also be that tumblr is blocking its api to your network if you use something like hide.me. It could also be that someone on that network is using the api already, thus your requests are dropped because they are already above the limit.

Did you set anything in the HTTP Proxy of TumblThrees settings?

**Comment by johanneszab** [comment]
I'm closing this since I already think this has nothing to do with TumblThree.

**Comment by zzf859313645** [comment]
Thank you for your help ,i can access it but must use vpn .I'm using lantern now. I also thought it was VPN's problem，i will  try something else. thank you and your work again.

**Comment by zzf859313645** [comment]
The problem is resolved. I just have to manually set the proxy port.
